### ISSUE TITLE
My led still not working

### ISSUE THREAD

**Issue by eengamer** [onlaj/Piano-LED-Visualizer#103]
I recieved my new psu today and my led strips still arent working what could be the problem??

**Comment by eengamer** [comment]
![20200402_132115](https://user-images.githubusercontent.com/61322147/78243882-def22c80-74e4-11ea-830a-ec30cdf5c718.jpg)
My first led looks like this but i dont think that this is the problem because my other strip also doesnt work and that one is normal

**Comment by onlaj** [comment]
Can you post it in old issue to keep it clean? Thanks :)
