### ISSUE TITLE
Visualizer error

### ISSUE THREAD

**Issue by Roloo38** [onlaj/Piano-LED-Visualizer#104]
hello, while I was playing piano, I got this error in visualiser, and now I can't run it again because I still get that error. any help?
![Screen Shot 2020-04-04 at 19 23 41](https://user-images.githubusercontent.com/55906704/78458282-cd617e00-76b8-11ea-9f3d-a6421a770d2b.png)

**Comment by onlaj** [comment]
Try to restart settings to default.

**Comment by Roloo38** [comment]
and how can I do this? I can't access visualiser menu

**Comment by onlaj** [comment]
Replace "settings.xml" with original file.

**Comment by Roloo38** [comment]
thanks!
