### ISSUE TITLE
Midi file speed issue

### ISSUE THREAD

**Issue by aisjamming** [onlaj/Piano-LED-Visualizer#107]
Hi, I just wanted to thank you for your life changing software, it's honestly tip top. I just had a question, the midi files that I record via the raspberry pi zero are slower than if I were to just record midi though my PC. Its not off by much but I can't seem to sync my video of me playing and the synthesia because of it when trying to make a video. When I record though my PC I am able to sync to the video but the video and the synthesia are always different lengths when I record though the pi. Any ideas?

**Comment by Kadnium** [comment]
Check out this #21
