### ISSUE TITLE
Lights staying on / sticking.  Notes randomly not responding.

### ISSUE THREAD

**Issue by bckl100** [onlaj/Piano-LED-Visualizer#11]
I have the full set up, and it seems to work ok, but lights remain on after pressing occasionally and sometimes pressed notes don't make the lights come on.  I'm unsure if this is code issues or just the performance of the hardware.  The LCD screen remains working and i see no errors on ssh/terminal.

**Comment by onlaj** [comment]
Run tests/printmidimessages.py and check if all notes are received correctly.

**Comment by bckl100** [comment]
Thanks - I could see some errors with note off and on not transmitting. I have managed to fix this with a change of hardware connection.
