### ISSUE TITLE
Skipping LED's

### ISSUE THREAD

**Issue by cercyo** [onlaj/Piano-LED-Visualizer#111]
Hello!
First of all thank you for this wonderfull project!
Could you please so kind to help with my issue?

My piano is Yamaha P-45 (88 keys)
My LED-strip is WS2812B 144 diods  per metr (http://ledreklamashop.ru/goods/Adresnaya-svetodiodnaya-lenta-RGB-WS2812B-5-Volt-SMD5050-144-LED-LUX-class?mod_id=213608059#show_tab_3)

The first key on the piano turns on the third diode
The second key on the piano turns on the fifth diode

Why it isn't start from first diode and don't turn on 2 didods instead of one?

![image](https://user-images.githubusercontent.com/64559075/80647450-2aaddc80-8a77-11ea-94eb-34da0995ff4e.png)

![image](https://user-images.githubusercontent.com/64559075/80647466-2ed9fa00-8a77-11ea-81a4-89d2a1896a02.png)

**Comment by onlaj** [comment]
Hey, I designed it this way. If you want to light more keys with one key press you can set in visualizer settings that it will light 3 leds.

**Comment by cercyo** [comment]
Thank you! It's perfect for me!
