### ISSUE TITLE
Connection pc - Raspberry not work

### ISSUE THREAD

**Issue by monttix** [onlaj/Piano-LED-Visualizer#112]
Hello, I connect my piano to rasp and project works, but when connect also pc (with a midi usb Y cable) raspberry not work. I need to connect the usb of piano to pc and rasp with cable. How I can?

**Comment by onlaj** [comment]
http://compasflamenco.com/midi-c-3/midi-usbusb-p-4.html
You connect one side to RPi and second to your PC. Piano will be still connected to RPi, so you need usb hub because RPi Zero has only one usb port.
