### ISSUE TITLE
Color fade between to colors

### ISSUE THREAD

**Issue by eengamer** [onlaj/Piano-LED-Visualizer#114]
Hello, i was wondering if there is an way you can add a feature that the leds go from 1 chosen color amooth to the other color. Like in the picture i pinned to this one.
![il_570xN 1810262432_fufy](https://user-images.githubusercontent.com/61322147/80999514-1a19af80-8e45-11ea-92ef-2639014cf942.jpg)

**Comment by eengamer** [comment]
If you do this. When will this come out?

**Comment by vzoltan** [comment]
you can play with the settings, where you can set the rainbow effect, 

mine is set to -15 30 0
and that gives a nice smooth gradient from deep red to greenish yellow, from low to high, left to right.

i dont rememeber wher is it exactly in the menu, but in the settings.xml its like this:


```
<fadingspeed>10</fadingspeed>
<color_mode>Rainbow</color_mode>

<rainbow_offset>-15</rainbow_offset>
<rainbow_scale>30</rainbow_scale>
 <rainbow_timeshift>0</rainbow_timeshift>
```

**Comment by eengamer** [comment]
am trying it right now but somejow it is only staying on blie and there is no gradient even tho i pit in the colord

**Comment by onlaj** [comment]
Works for me, did you update all files?
![eZnelix](https://user-images.githubusercontent.com/9073428/118705713-da87f080-b818-11eb-9867-d3b2fd50b635.png)

**Comment by eengamer** [comment]
i think i have to rewire my wires. they got loosen up a bit and thats what causing it to not function that well. or my powersupply may have a fault

**Comment by onlaj** [comment]
If it doesn't help we can try to debug it.
Inside [this](https://github.com/onlaj/Piano-LED-Visualizer/blob/master/visualizer.py#L2337) method add line with

`print ("position: "+str(position)+" leds: "+str(ledstrip.led_number)+" start: "+str(self.gradient_start["red"])+"end: "+str(self.gradient_end["red"]))`

run modified code, try to play something and copy paste here output from console.
