### ISSUE TITLE
Start on first pixel/LED not the 3rd

### ISSUE THREAD

**Issue by Berrance** [onlaj/Piano-LED-Visualizer#117]
HI, How can I make it so that the first led to lights up instead of the 3rd?

I have fiddled with note_offset = 0 changing it to a 2 and while this made the fist led light up it messed with the spacing for the rest of the keys. I tried reducing the self.LED_COUNT down to 174 but that made the last key stop working.

Basically I want the visualiser to run on 174 pixels instead of 176 but start on led 1 instead of led 3.

The reason I want to do this is once I put the led stip in the LED profile it is longer than the keys and wont fit within the piano.

I would prefer to do this in software but if I can't my solution is to fold the first two leds behind the rest within the led profile

**Comment by onlaj** [comment]
https://github.com/onlaj/Piano-LED-Visualizer/issues/119
