### ISSUE TITLE
RPi Bluetooth plus synthesia learning set up

### ISSUE THREAD

**Issue by bckl100** [onlaj/Piano-LED-Visualizer#12]
I don't think this in the scope of an 'issue' but just some extra information for those that try. Synthesia learning set up with RPi bluetooth only worked for me using Synthesia from a windows pc.  I tried previously with an ipad and macbook, which both gave erratic results for the 'learning' LED lights (when setting visualiser to RPiBluetooth as input).

**Comment by ZoeESummers** [comment]
Did you ever come to understand why? It's very strange as usually the bluetooth stack on iOS / macOS is significantly better than on other devices.
