### ISSUE TITLE
LED backlight does not stay on after playing key

### ISSUE THREAD

**Issue by kimaluco17** [onlaj/Piano-LED-Visualizer#120]
Greetings,

I configured the LED strip with the backlight setting and ran into an issue with it. When the key is pressed down it correctly lights up, but the backlight does not stay on after the key is lifted.

Not a huge deal since the surrounding lights stay on, but when adjacent mode is also enabled it leaves the surrounding lights off as well, so one could just swipe all the keys and the backlight for all the LEDs would stay off.

**Comment by onlaj** [comment]
Fixed :)
