### ISSUE TITLE
Traceback issues

### ISSUE THREAD

**Issue by imagemas** [onlaj/Piano-LED-Visualizer#125]
Don't run app. Midi Connected. Ledstrip connected correctly.
![iss](https://user-images.githubusercontent.com/66170486/83330211-ed847680-a2d0-11ea-843d-283416eb99d8.JPG)

**Comment by onlaj** [comment]
Try to install different rtmidi library
https://github.com/mido/mido/issues/145

**Comment by imagemas** [comment]
Thank you, the problem was solved by reinstalling rtmidi.
