### ISSUE TITLE
Input Output Ports

### ISSUE THREAD

**Issue by harryG15** [onlaj/Piano-LED-Visualizer#131]
Hi Onlaj, just wondering - I successfully completed your Build around 6 or 7 months ago but left it for a while... I picked it up again recently and rewired some stuff to make it neater & thought... I should get the new updates from the ‘master’! 

I noticed you don’t have an ‘output’ anymore and my LED strip isn’t working? 
Could either my wiring or maybe I need the output - for it to work?
Let me know
Many thanks

**Comment by onlaj** [comment]
Hey.
No, output port is not needed, it was a placeholder. It must be your wiring.

**Comment by harryG15** [comment]
Ahh that’s annoying! 
Can I ask?
![EB3548D1-008E-426B-AAB2-3D9538F3306C](https://user-images.githubusercontent.com/56074117/85391881-aa6d9a00-b542-11ea-8afa-16ea80ce094f.jpeg)
Is this wiring ok?

**Comment by onlaj** [comment]
Yep, it's good.

**Comment by harryG15** [comment]
Sweet! Can I let you know if I get in any more trouble?

**Comment by onlaj** [comment]
Sure :)

**Comment by c4charge** [comment]
Quick heads up, the raspberry in the video is not a pi Zero. so the LCD connector is "north" instead of "south" if you understand what I mean. (just throwing it out there because I made that mistake lol)

**Comment by harryG15** [comment]
![image](https://user-images.githubusercontent.com/56074117/85393526-105b2100-b545-11ea-921c-587fe9a48e20.jpg)
So is this right?

**Comment by onlaj** [comment]
Seems to be right, does it work?

**Comment by harryG15** [comment]
No, but somethings just occurred to me that I’m powering the Pi & the LED power supply through extension cable!

**Comment by harryG15** [comment]
![C24FAE7D-4AF7-48E4-AA28-D02157A42C6F](https://user-images.githubusercontent.com/56074117/85396571-e5270080-b549-11ea-856e-9f54111e56e7.jpeg)
If you wouldn’t mind taking a look 
Much appreciated

**Comment by harryG15** [comment]
Excuse the silly coloured wiring - tried to explain it

**Comment by harryG15** [comment]
![image](https://user-images.githubusercontent.com/56074117/85396733-24ede800-b54a-11ea-9cd2-af51793f62ee.jpg)
This is also direction of arrows?

**Comment by onlaj** [comment]
Everything looks fine, it should work :)
