### ISSUE TITLE
Sustain Pedal

### ISSUE THREAD

**Issue by harryG15** [onlaj/Piano-LED-Visualizer#133]
Hi, just wondering with the midi that's recorded on the device.... Ive transferred it to Logic Pro X to edit it, and can't see any sustain information used by pedal? 
There's definitely velocity, but can't seem to find any information with pedal? 
Let me know if I'm not seeing it? 
Thanks

**Comment by onlaj** [comment]
Fixed https://github.com/onlaj/Piano-LED-Visualizer/commit/9b3c23064c6b255c7037eae5c5ebd79324155993
