### ISSUE TITLE
Bluetooth connect PC problem

### ISSUE THREAD

**Issue by Kliklijoker** [onlaj/Piano-LED-Visualizer#135]
after issue aconnect -l I got,

client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 20: 'Roland Digital Piano' [type=kernel,card=1]
    0 'Roland Digital Piano MIDI 1'

and I can't see RPi Bluetooth on my PC

**Comment by onlaj** [comment]
Hey, try to use Blueman app to connect your PC with RPi.

**Comment by Kliklijoker** [comment]
After I try use blueman app I found my RPi zero can't detect any Bluetooth signals, I already try two pc and my phone(Android), in blueman app I can't see any device, is my RPi Bluetooth broken?

**Comment by Kliklijoker** [comment]
I already bought a new RPi zero, I very sure is my hardware already broken.
