### ISSUE TITLE
Led backlight doesnt worke well with vitualizer

### ISSUE THREAD

**Issue by safibeyond** [onlaj/Piano-LED-Visualizer#138]
I have a problme with backlight 
When backlight is on some of led above keys dont turn on when i press theme 
I mean, i set white color for backlight and red color for vitualizer and when i press C it should be a red light above the C key 
But some times near 5 % of times it doesnt worke and the light still white as i set up for backlight 
I think its a bug and i ask some other guys about this 
and some of theme have the same problme
What can i do for this? 
And if i dont set up a backlight vitualizer workes with no problme

**Comment by onlaj** [comment]
Fixed
