### ISSUE TITLE
Sticky LED's with bluetooth on Synthesia

### ISSUE THREAD

**Issue by ajayprk** [onlaj/Piano-LED-Visualizer#139]
We configured the Bluetooth section and were successfully able to connect with an iPad and also a mac. The LED's light up and sometimes stay lit until the same key is pressed again. The piano also sounds different and some keys sound louder than how I how played them or sometimes wont stop playing at all. Is this something others have faced/ fixed?
Any tips to resolve would be appreciated.

Other Info:
I select my visualizer as both the input and output in Synthesia and I changed the Keylight to "Finger-based channel"

**Comment by onlaj** [comment]
Hey.

>The LED's light up and sometimes stay lit until the same key is pressed again
It probably means that it dropped some notes because of BT connection.

>The piano also sounds different and some keys sound louder than how I how played them or sometimes wont stop playing at all.
When is this happening? When you are playing some song with Synthesia or all the time after connecting your iPad?
