### ISSUE TITLE
Midi cant record the pedal

### ISSUE THREAD

**Issue by safibeyond** [onlaj/Piano-LED-Visualizer#141]
I have probleme with the midi record part 
When i play a song by the using of damper pedal 
But some how when midi recorded and play it on visualizer or send it in my computer its like i didnt use pedal at all 
I dont know its a bug or what but it affects the whole song 
What should i do now?

**Comment by onlaj** [comment]
Fixed https://github.com/onlaj/Piano-LED-Visualizer/commit/9b3c23064c6b255c7037eae5c5ebd79324155993
