### ISSUE TITLE
Key lights not quite aligned with keys.

### ISSUE THREAD

**Issue by colindmurray** [onlaj/Piano-LED-Visualizer#144]
Is there any way to adjust the key separation? I'm having a small problem where the as the keys go lower or higher the light alignment drifts slightly. It could be my keyboard is slightly non-standard and has narrower keys than usual.

Middle C is perfectly aligned:
![image](https://user-images.githubusercontent.com/3422503/90041620-8d7a5b00-dc97-11ea-86b0-477626fd87d8.png)

My high F# is off by maybe a single LED
![image](https://user-images.githubusercontent.com/3422503/90041715-ad118380-dc97-11ea-9eda-db326e708e33.png)

My low F is likewise off by maybe 2 LEDs
![image](https://user-images.githubusercontent.com/3422503/90041777-c3b7da80-dc97-11ea-9fe1-a8b826404f7e.png)

**Comment by onlaj** [comment]
Hey.
In the [visualizer.py](https://github.com/onlaj/Piano-LED-Visualizer/blob/master/visualizer.py) file you can find code under the comment 

>  #changing offset to adjust the distance between the LEDs to the key spacing

```
if(note > 92):
            note_offset = 2
        elif(note > 55):
            note_offset = 1
        else:
            note_offset = 0
```
You will have to tweak this part to fit your keyboard.
