### ISSUE TITLE
Last few keys don't light up

### ISSUE THREAD

**Issue by didgeridoooo** [onlaj/Piano-LED-Visualizer#145]
Everything works as expected, but the last few keys dont light up on my setup. I have checked the voltage across 5V and GND and I am getting a little over 5V at the end. When I turn on the scanner animation, and it hits the dead area, it is blank for a period of time which makes me believe the pi is operating correctly and sending the signal, but the strip is not properly reacting to it. Is there anything I can do to troubleshoot the issue and see why it stops at that point?

**Comment by onlaj** [comment]
Looks like a damaged strip, you would have to measure whether the voltage is going through the data line.
