### ISSUE TITLE
Bluetooth Recognition & Android

### ISSUE THREAD

**Issue by chrapm1** [onlaj/Piano-LED-Visualizer#148]
The RPi does not pickup the android bluetooth even when using apps such as BLE Midi.  The problem seems to be on the android side, is there any workarounds or ways to force the recognition?

Apple devices show up on the RPi the correct way.

Any troubleshooting steps or solutions will be appreciated.

**Comment by inonoob** [comment]
I'm not sure if that helps but I had for a different project issue with Bluetooth Low energy and Android. The thing is with bluez, it start in Bluetooth Classic mode and Bluetooth Low Energy mode. 

try editing the following file `/etc/bluetooth/main.conf` and change the following: 

```
# Restricts all controllers to the specified transport. Default value
# is "dual", i.e. both BR/EDR and LE enabled (when supported by the HW).
# Possible values: "dual", "bredr", "le"
#ControllerMode = dual 
``` 
```
ControllerMode = le  
```

then reboot. 

you can check the status if you tip `btmgmt` and then tip `info` you then should see 
```
hci0 new_settings: powered bondable le secure-conn
```

That help with my project a lot.
