### ISSUE TITLE
Do anybody have ready iso file with this project?

### ISSUE THREAD

**Issue by bitterspy** [onlaj/Piano-LED-Visualizer#15]
Hi, im struggling with lots of errors and have no time to do with this project anymore. Do anybody have working system and is able to share just ready to download iso image from SD card? If yes please share with me. I will be very gratefull. Thanks

**Comment by vzoltan** [comment]
Hi, im also interested in a working img file.

Could someone pls dd his/her sd card and share?

**Comment by konradqwerty** [comment]
Try PianoTutor, I also couldn't run Onlaj's

**Comment by vzoltan** [comment]
thx, bud id like to use my pi zero + led setup.

**Comment by vzoltan** [comment]
Ill will share mine.
almost done, everything working, except i cant see my rpi-bt in synthesia on my windowss.
the leds are on while i play on the piano, now i need to find a fix for my synthesia connection or bt connection problem, and then ill share the image.

**Comment by rickstaa** [comment]
I created a backup of my working img using dd it can be found [here](https://sourceforge.net/projects/piano-led-visualizer/). Let me know if it works.
