### ISSUE TITLE
Error while runnign visualizer.py

### ISSUE THREAD

**Issue by Roloo38** [onlaj/Piano-LED-Visualizer#152]
Hello,thanks again for the project:D. When  i try to run visualizer.py i got an error: 

  File "visualizer.py", line 893
    else:
        ^
TabError: inconsistent use of tabs and spaces in indentation

any ideea why?

![image](https://user-images.githubusercontent.com/55906704/95016739-9bc47200-065d-11eb-93e9-ed66144ddb6b.png)

**Comment by onlaj** [comment]
Hey. Try to use "python" instead of "python3" in your command.

**Comment by Roloo38** [comment]
Sorry for late response. I used python 2.7 and it worked. Thanks!

**Comment by onlaj** [comment]
I fixed indentation in last update so it should now works with python 3.
