### ISSUE TITLE
Synthesia Not Lighting LED's on Playback or Practice Mode

### ISSUE THREAD

**Issue by donwatermelon** [onlaj/Piano-LED-Visualizer#160]
Hi Piano-LED-Visualizer Community. 

I'm stuck trying to diagnose a LED/Synthesia problem and I'm hoping for some help. With regards to setup:

Raspberry Pi Zero W (via Bluetooth) with 1.44" LCD Hat
Yamaha Arius YLP142
MacOS Catalina
Synthesia 10.6.5425 (Free, not Unlocked)

The LED strip, RPI, bluetooth and MIDI configuration all **appear** to be fine as the LED strip lights up/responds to piano key presses without issue. Synthesia detects the keypresses displaying on the virtual keyboard and plays back the audio through the laptop when My Notes is enabled 

The issue is that when using playback/practice mode I cannot get the LEDs to light up with the relevant keys played or to be played. I've tried various settings combinations but can't seem to get these parts working. As to what they are:

Input Settings:
Synthesia Virtual Piano - Off
RPI - On

Output:
Built-In Midi - Off
RPI - Mine; Key Lights (Finger-Based); Midi Channel - Omni

I'm sure I'm doing something stupid but can't figure it out so hopefully, someone might be able to tell me what that might be. Appreciate any help anyone could offer, on the PI or otherwise.

Thanks in advance

**Comment by onlaj** [comment]
Hey.
Did you change input in Visualizer settings to your BT connection?
