### ISSUE TITLE
Cannot find WS2812B LED Strip 1.5m with 144 

### ISSUE THREAD

**Issue by dmitryallen** [onlaj/Piano-LED-Visualizer#163]
Hello, 
nice project. 

Could you please provide more information about compatible strips ?
In spec we have **WS2812B LED Strip (at least 1.5m with 144 diodes/meter)**

I could find a strip 1.5m with 144 usually we have **1m** 144 
Is there alternative ? 
**Or it possible to buy two strips with 1m 144 and concatenate them ?** 

Thanks, 
Dmitry

**Comment by xxx02** [comment]
You can buy two and solder them together. There must be a link for 2m strip.

**Comment by dmitryallen** [comment]
Many thanks, just found 2m strip on Ali Express
