### ISSUE TITLE
LED lights

### ISSUE THREAD

**Issue by toast122** [onlaj/Piano-LED-Visualizer#166]
They do not respond to key presses, and the lights are always on. 

Edit: Only backlights light up, and i cant use solid colors. I got to use the RGB in backlights for the colors, however animations work as well.

Edit: They work when i use midi cables, but not with a printer USB cable. And i would like the latter in order to be able to record my playing.

Any help/suggestions are appreciated. Thank you

**Comment by onlaj** [comment]
> They work when i use midi cables, but not with a printer USB cable

RPi must be connected to a device which acts like midi hardware.
You can record your playing using visualizer.

**Comment by toast122** [comment]
I'll try that and let you know soon. Thank you!
