### ISSUE TITLE
Led Color Confusion on Synthesia Learning

### ISSUE THREAD

**Issue by xxx02** [onlaj/Piano-LED-Visualizer#168]
I have successfully connected pi with pc over RTP. Thanks for that @onlaj
I have 2 questions:
- Synthesia blue and green color works but when a note comes the first time it lights up default color not blue or green on the second come of the same note it's ok. Every new notes just light up default color. I have tried every option in skipped notes as mentioned but didn't work at all.
- Is there any way for assigning ports without using terminal. We have to use the command `aconnect  20:0 128:1` and `aconnect 128:1 20:0` every time after restart. Maybe there can be an option in visualizer menu? And also for restarting rtpmidi and resetting port connections.

**Comment by onlaj** [comment]
- Does this happen with every midi file?
- I'm working on that

**Comment by xxx02** [comment]
I just tried only synthesia's songs.

**Comment by luizzitol** [comment]
I am experiencing exactly the same on Syntesia. The first time a note is coming will get default color and then it will go to green or blue... Then in the middle of the song it will randomly use the default color instead of the green/blue from Syntesia.

Did you find any solution to this xxx02?

**Comment by xxx02** [comment]
Not yet :/
