### ISSUE TITLE
LEDs don't respond to key presses

### ISSUE THREAD

**Issue by devucsb** [onlaj/Piano-LED-Visualizer#169]
Thanks so much for the help in advance.

My keyboard/printer cable successfully sends MIDI info from the keyboard to my PC but I'm not having success seeing the visualizer when I press keys. However, when I play animations the LEDs do work.

I haven't soldered the wires to the pins so perhaps it's an issue with how I'm curling the wires around the pins / using heat-shrink to avoid the wires from touching other pins? I'm using a MIDI port shown in the following image. 

![image](https://user-images.githubusercontent.com/61645829/101304367-ee084780-37f4-11eb-92dd-ed41643663d6.png)

**Comment by onlaj** [comment]
Do you see your piano under "input" in ports settings?
Run tests/printmidimessages.py to check if midi meesages are received.
