### ISSUE TITLE
Fixing PLV screen resolution

### ISSUE THREAD

**Issue by ketsogo** [onlaj/Piano-LED-Visualizer#171]
The led visualizer system showed up but it just looks like this...and btw how do you transfer recorded midi to pc wirelessly??
![IMG_20201214_223304](https://user-images.githubusercontent.com/75939484/102098254-ef271d80-3e61-11eb-98ee-ed99e6adac7f.jpg)

**Comment by onlaj** [comment]
Try to reattach screen hat, looks like faulty connection.

>and btw how do you transfer recorded midi to pc wirelessly??

 Via SSH using some ftp client.

**Comment by ketsogo** [comment]
Ok thanks... I'll try if it works

**Comment by ketsogo** [comment]
I tried many times but it still doesnt work

**Comment by onlaj** [comment]
Seems like your hat or RPi might be damaged. Try to download some demo code for this screen and test if it works https://www.waveshare.com/wiki/File:1.44inch-LCD-HAT-All-Code.7z

**Comment by ketsogo** [comment]
How do I use this code??.. Sorry just a beginner hehehe

**Comment by onlaj** [comment]
@ketsogo download the 7z file, unpack it and transfer RaspberryPi\python\ to your RPi.
Then launch the demo code with
`sudo python key_demo.py`

**Comment by ketsogo** [comment]
Do I transfer it on the SD card?

**Comment by onlaj** [comment]
This or just use sftp. Put it in /home directory and launch the demo.

**Comment by ketsogo** [comment]
The file you sent is for 1.44 inch ... is it okay if my lcd hat is 1.33?

**Comment by onlaj** [comment]
Either I missed your mention of the display type or you didn't mention it at all. If you want to run a script on a 1.3 inch screen you need to add the appropriate parameter, did you do that?

> If you are using WaveShare 1.3inch 240x240 LED Hat instead of 1.44inch 128x128, add this instead: sudo python3 /home/Piano-LED-Visualizer/visualizer.py --display 1in3 &

https://github.com/onlaj/Piano-LED-Visualizer/blob/master/manual_installation.md

**Comment by ketsogo** [comment]
yes I added the appropriate one for the 1.33

**Comment by onlaj** [comment]
In that case get demo code for your display and test it https://www.waveshare.com/wiki/File:1.3inch_LCD_HAT.7z
