### ISSUE TITLE
Idea: LED stripe could be used show the right keys for different scales

### ISSUE THREAD

**Issue by McSpitz** [onlaj/Piano-LED-Visualizer#182]
This is probably a very useful feature which could be implemented to show the right keys for each scale.

kr
Alex

**Comment by SivanDuijn** [comment]
i'd like to give this a try

The idea is to select in which scale you are playing, and when a key is pressed that is in the scale, a different color is shown than for keys that don't?
Or that the backlighting shows the keys in the selected scale?

(i hope the first one, as i'm already kinda been working on that a little)

**Comment by SivanDuijn** [comment]
ok, the one where the pressed key is colored depending on if its in the selected scale is working!
