### ISSUE TITLE
LED does not respond

### ISSUE THREAD

**Issue by MrNazers** [onlaj/Piano-LED-Visualizer#189]
Hello, my LED strip does not work with the software, light works when I connect the data to port 14 of the gpio ( only some RGB ). The campanella doesn't work either, I have already tested the connections to the multimeter and the led band receives a 5.5V and 3.8V for the data.
My keyboard is well recognized by the raspberry, and the different led test doesn't work (neopixel error or no light).

![146921482_790144611593935_591236540132984172_n](https://user-images.githubusercontent.com/32036424/107420092-d319c280-6b18-11eb-8564-72cbcf0aad4c.jpg)

**Comment by SivanDuijn** [comment]
You could try to connect the data wire of the led strip to gpio pin 18 and test the led animations.
![afbeelding](https://user-images.githubusercontent.com/32020138/107580022-43e2dc80-6bf6-11eb-81f1-5a46d48a8408.png)

Hope this works

**Comment by MrNazers** [comment]
Thanks Sivan , I checked all the connections, connected to gpio 18 ,then 12 as indicated in an old post,but the leds remain off :(

**Comment by MrNazers** [comment]
I changed the raspberry, still the same problem I'm starting to think it's coming from my cabling. 

![Inked150177873_519241322377454_874465587421487182_n_LI](https://user-images.githubusercontent.com/32036424/107857515-0d43d680-6e2f-11eb-8e29-815376f0f71f.jpg)


I have removed the red and white wire from the LED because they are useless, I'm not sure about the surrounded cabling.

**Comment by SivanDuijn** [comment]
yes you don't those wires, but the other wires should be connected as follows:
![afbeelding](https://user-images.githubusercontent.com/32020138/107858110-c2c45900-6e32-11eb-96ab-61e483984df4.png)
So in you image this would look like
![afbeelding](https://user-images.githubusercontent.com/32020138/107858187-32d2df00-6e33-11eb-82a8-7ca31b1743dd.png)

From the led strip you need to connect the white wire to the black ground cable coming from the power supply (and the pi), the green wire to the white signal wire coming from the pi, and the red wire to the red wire coming the from the power supply.

This should work

**Comment by MrNazers** [comment]
thank you very much! At the beginning it didn't work but the problem came from one of the segment of the LED that wasn't working, so check it out, I finalized everything, it works great, but last problem since I removed a segment of the LED strip the keys are shifted ...you know how to tell the software to start at the 30th led for example ?

**Comment by antonio-qp** [comment]
LED Strip Settings > Shift

**Comment by MrNazers** [comment]
The shift works but it doesn't solve all my problem ^^ I tried to change the led count too but nothing to do the LED's are stuck at number 64. Any solutions ? 

![Uploading IMG_20210218_172058.jpg…]()
