### ISSUE TITLE
is it okay?

### ISSUE THREAD

**Issue by hyuny223** [onlaj/Piano-LED-Visualizer#192]
is it okay to use 288 leds strip itself or should I cut 2m strip(288 leds) into about 1.5m?

I used to have overheat problem several times so I want to know.

**Comment by onlaj** [comment]
Hey. You should cut it to the length of your piano.

**Comment by hyuny223** [comment]
Is there an electrical problem if I don't cut the strip?

**Comment by onlaj** [comment]
As long as your PSU is able to provide enough amps it should be fine, for 288 leds @100% power you would need PSU with 17A. If you don't have that much power just avoid lighting more than few LEDs at the same time and you should be fine.

**Comment by hyuny223** [comment]
thanks for your advice!
