### ISSUE TITLE
Default port connection?

### ISSUE THREAD

**Issue by luizzitol** [onlaj/Piano-LED-Visualizer#193]
Hi Onlaj,

First thank you for this amazing project. I was wondering if there is any way to select a "default" input and playback port, in a way that we do not have to set them every time we reset the Rpi.

Many thanks
Luis

**Comment by onlaj** [comment]
Hey, it's already done (thanks to @SivanDuijn https://github.com/onlaj/Piano-LED-Visualizer/pull/186 ) for input port, in the next update I will add support for playback port too.
