### ISSUE TITLE
3d printing model too tall

### ISSUE THREAD

**Issue by luizzitol** [onlaj/Piano-LED-Visualizer#194]
Hi Onlaj,

I was wondering if you have the .skp from Rpi case model you provide on your repository, as I would like to be able to edit the height of it but unable to do it with the .stl file.

Many thanks
Luis

**Comment by onlaj** [comment]
Hey, unfortunately no, but you can still edit stl file, that's how I edited original model.

**Comment by luizzitol** [comment]
Thank you for your reply, I have tried to edit it with no luck so far. What software do you recommend? (I guess I have a lot of learning to do ahead)
