### ISSUE TITLE
Lights light up

### ISSUE THREAD

**Issue by glootkoopshire** [onlaj/Piano-LED-Visualizer#20]
Are the lights supposed to light up when you connect them to the power supply or do they only light up when you connect them to the PI and run the program? I got the power supply you linked on Amazon, im thinking i have to set the brightness to 50% in the program for it to work but im not sure

**Comment by onlaj** [comment]
They need proper signal, so connecting it to power supply won't light them up.

**Comment by glootkoopshire** [comment]
ah ok, tyvm for the help
