### ISSUE TITLE
Cutting the LED strip

### ISSUE THREAD

**Issue by ababnoy** [onlaj/Piano-LED-Visualizer#201]
I have to cut my LED strip because it is too long but I don't know where to cut it and I don't see the cut lines either... could someone show me where? I would appreciate the help.

**Comment by onlaj** [comment]
Hey, check the picture: https://i.imgur.com/Vssj89W.png

**Comment by ababnoy** [comment]
Thanks for your help, I've managed to cut the led strips properly : )
