### ISSUE TITLE
Chords are not played  ?

### ISSUE THREAD

**Issue by siriushex** [onlaj/Piano-LED-Visualizer#205]
1. When playing from Synthesia, chords are not played, only one LED lights up. ? how to fix ?

2.How to run a midi file from the songs folder in the command line, without a LCD screen ?

**Comment by EmanuelFeru** [comment]
I am not sure I can help on Synthesia topics, but recently I implemented Learning without Synthesia:
https://github.com/onlaj/Piano-LED-Visualizer#learning-to-play-midi-files
Maybe for your 2nd point it can be useful.
