### ISSUE TITLE
No LCD hat

### ISSUE THREAD

**Issue by MadhavMantri28** [onlaj/Piano-LED-Visualizer#208]
Hello there!
I have coded it. However I do not have the LCD hat and as far as I know I wont be able to get it in my area anytime soon. I have 3.2 inch waveshare LCD hat but I dont think that is compatible. I wanted to know how can I handle the LED without the LCD hat. 
Thank you.

Edit 1 : I figured out that by changing RGB in the starting of settings file, the colors are changing. But I dont know how to get the rainbow effect and other things. I want to learn few basic stuffs like recording and saving midi and then when I will get the LCD it will be best. Can anyone help me here?

**Comment by onlaj** [comment]
Hello.
For color mode instead of "Single" you put "Rainbow" or "Speed" or "Multicolor".
Currently it's not possible to start recording midi without lcd hat.

**Comment by MadhavMantri28** [comment]
One more thing do I need to reboot the pi every time I make changes in the settings file?

**Comment by onlaj** [comment]
No, but you have to restart the script.

**Comment by MadhavMantri28** [comment]
Hello. I just got my LCD hat and its working fine. However, I am just able to use the bottom and the up key. The jpress and right left and other key 1 2 3 are not working. Can you please help me here?

**Comment by onlaj** [comment]
Try to reconnect the hat, make sure all pins are inserted securely.

**Comment by MadhavMantri28** [comment]
Yes I did everything and I have pinned them securely but I dont think this is of any help. I mean I changed the pin number in the code for down. For example if down arrow key was 16 and jpress was 13, I flipped them and found that jpress is working too. So this tells my LCD hat is fine. I dont know.

**Comment by onlaj** [comment]
Get demo code and check if it works there https://www.waveshare.com/wiki/File:1.44inch-LCD-HAT-All-Code.7z

**Comment by MadhavMantri28** [comment]
I am really sorry but I dont get what I have to do. Can you please elaborate. Thank you very much.

**Comment by onlaj** [comment]
Download demo code, unzip, go to RaspberryPi folder and copy paste Python folder somewhere to your RPi, for example to /home/ catalog. Then run the key_demo.py

**Comment by MadhavMantri28** [comment]
![image](https://user-images.githubusercontent.com/80873616/113310848-4a542180-9326-11eb-86ac-586e3b68ca75.png)

It is showing me this error.

**Comment by onlaj** [comment]
Run it with python instead of python3 or add parentheses to every print.

**Comment by MadhavMantri28** [comment]
I did run with python it is showing me import error : no module named LCD_1in44

**Comment by onlaj** [comment]
Is file LCD_1in44.py in the same folder as file key_demo.py?

**Comment by MadhavMantri28** [comment]
![image](https://user-images.githubusercontent.com/80873616/113400742-eb42eb00-93bf-11eb-8884-5ff165e96f10.png)
I am getting this when I run the program and use my lcd hat.

**Comment by onlaj** [comment]
So it works with demo code, that's really weird.
Starting from this [line](https://github.com/onlaj/Piano-LED-Visualizer/blob/master/visualizer.py#L2378) you can find code responsible for detecting key presses. As you can see it looks the same for every key (excluding key 2 and key 3 which has additional functions) and I have no clue why only two of them are working.

**Comment by MadhavMantri28** [comment]
I did the whole coding again too yesterday and the issue remains the same.  Can I do something like this 
Since my down key and up keys are working, can I change the code of down key and put some other function?
