### ISSUE TITLE
Error when installing LED visualizer

### ISSUE THREAD

**Issue by ababnoy** [onlaj/Piano-LED-Visualizer#209]
![Untitled](https://user-images.githubusercontent.com/78776244/111625507-df83f000-8827-11eb-9009-8c8433766e29.png)
This happens when I entered "sudo pip3 install -r requirements.txt". I tried restarting and I got the same results.

**Comment by SoosOnBread** [comment]
Try this:
apt-get install libjpeg-dev zlib1g-dev
pip3 install Pillow
sudo pip3 install -r requirements.txt

Source: https://stackoverflow.com/questions/69624327/failed-building-wheel-for-pillow
