### ISSUE TITLE
New pre-build img

### ISSUE THREAD

**Issue by vzoltan** [onlaj/Piano-LED-Visualizer#213]
https://github.com/onlaj/Piano-LED-Visualizer/releases/tag/v1.00

Hi @onlaj , with all the new feature from @EmanuelFeru, are you going to make a new img file?

Thx.

**Comment by onlaj** [comment]
Yep, after I finish autoconnect to RTP MIDI.

**Comment by vzoltan** [comment]
Thanks :)
