### ISSUE TITLE
No learn on menu

### ISSUE THREAD

**Issue by cypomi** [onlaj/Piano-LED-Visualizer#215]
I'm not sure if I missed something but there is no Learn menu.

the only things that show up are

- LED Strip Settings
- Play MIDI
- Ports Settings
- LED Animation
- Display Settings
- Other Settings
- Shutdown options

Any help would be appreciated.

**Comment by onlaj** [comment]
Update Visualizer https://github.com/onlaj/Piano-LED-Visualizer#faq
