### ISSUE TITLE
Default MIDI input port

### ISSUE THREAD

**Issue by JustTomMcGee** [onlaj/Piano-LED-Visualizer#219]
Is there a way to auto select midi in port at startup? Quite a hassle to change it every time I boost up RPi

**Comment by onlaj** [comment]
Hey.
It should remember last used port as long as the name didn't change.

**Comment by JustTomMcGee** [comment]
I keep the OTG connected to MIDI unplugged but still have to manually select every time

**Comment by aquinodaniel1994** [comment]
I have the same problem, is there any solution ?
