### ISSUE TITLE
No playback port

### ISSUE THREAD

**Issue by Roloo38** [onlaj/Piano-LED-Visualizer#22]
After i do all The things, in write The comand for The visualizer 
> sudo -E python3 visualizer.py

And i got an error “no playback port” And The led doesnt light up when i play Piano :(
I want to Say that my Piano is Connected through USB cable to The raspberry, And The raspberry Find that port.
Any ideea Why?

https://imgur.com/a/SYTZ4cK

**Comment by onlaj** [comment]
Try to run /tests/printmidimessages.py" to check if RPi see messages from piano.

**Comment by Roloo38** [comment]
I did this and I got another error: “ModuleNotFoundError: No module named ‘mido’” 
I forgot to install something or why I got this error?

**Comment by onlaj** [comment]
If you installed everything from "requirements" file it should work.
Try without "3" in command
`sudo -E python visualizer.py`

**Comment by Roloo38** [comment]
I tried without “3” and I got the same error. I will reinstall the req and I’m coming back if I doesn’t work. Thank you :)

**Comment by Roloo38** [comment]
I reinstalled the requirements and I got another error: “ImportError: No module named webcolors 

https://m.imgur.com/gallery/cmngla9

**Comment by Roloo38** [comment]
Ok, so, I ran “sudo -E python3.7 printmidimessages.py” and the RPI see my piano (“inport set to rtmidiout client:rtmidi output 132:0
Inport set to USB ProKeys 88:USB ProKeys 88 Midi 1 20:0
Inport set to USB ProKeys 88:USB ProKeys 88 Midi 1 20:1) so this means that the rpi see my piano.
If I ran “sudo -E Python visualizer.py” I got the “no playback port error”
Do you know why?

**Comment by onlaj** [comment]
The most important is "inport", playback is needed when you want to play recorded midi.
What happens when you run printmidimesages.py and press piano keys? Does it print incoming messages?

**Comment by Roloo38** [comment]
No, it doesn’t print anything on the terminal, it just show the message with the piano name.
If I play piano keys, nothing happens

**Comment by onlaj** [comment]
So it seems your piano doesn't send any messages or RPi is not able to receive them. Does it work with PC or other equipment?

**Comment by Roloo38** [comment]
Yes, I record with pc and usb cable and the piano send messages to pc

**Comment by onlaj** [comment]
Well, I'm afraid that I can't help you. I had similar problem when I connected my piano through cheap midi to usb interface but it also didn't work with PC.

**Comment by Roloo38** [comment]
So tell me, the connection between the piano and the rpi is made using only an usb cable, right?

**Comment by onlaj** [comment]
In my case it is connected through midi to usb interface because my piano doesn't have USB.

**Comment by Roloo38** [comment]
Ok, I think I have an midi to usb interface, I will try with it and let you know if it works for me :D 
Thanks for helping
