### ISSUE TITLE
Connect touchDaw and Synthesia

### ISSUE THREAD

**Issue by AbrahamWisman** [onlaj/Piano-LED-Visualizer#222]
Question: Is it possible to connect touchDaw with Synthesia on Android? 
If yes:
   explain_how()

I have touchDaw demo installed.
I can connect with my rpi with rtp
I have synthesia full version on Android
but i dont see it as a input/output option in synthesia app.

I tried built-in USB-MIDI driver and Android M MIDI

**Comment by bradliegek3** [comment]
That is a very good question

**Comment by Pausejo** [comment]
Same here...

**Comment by AbrahamWisman** [comment]
@Pausejo I build the app "midi connector", its on the play store. It can connect synthesia (or other midi software) with RTP devices.
