### ISSUE TITLE
Led strips wont turn on

### ISSUE THREAD

**Issue by JustTomMcGee** [onlaj/Piano-LED-Visualizer#224]
I extended the wires with a pair of 3-pin connectors but now the LED strip wont turn on, unlike before.
RPi still boots up and reads the system image normally.
Is there any chance that the LED strip could be damaged? Also are there other possible issues?

**Comment by JustTomMcGee** [comment]
I bought the 3-pin connectors off Aliexpress so I don’t know if the wires could have any problems (mainly because their cheap)

**Comment by bobsmith1950** [comment]
checked resistance of each of the 3 wires from the led strip to their ends?
If the only thing you've done is extend them then start with that - could be bad soldering or a broken wire.

**Comment by JustTomMcGee** [comment]
I bought a new LED strip AND a new Raspberry Pi but the LED strip still won't turn on
I cut the 3 pin connector from the other end of the LED strip to connect to RPi (I cut at the right end where the arrow points to)
it's strange to me because in the video the 3 pin connector works fine
I'm suspecting the wires but do wires nicked from stripping stop working properly? (white wires connected to 3rd pin and green to 6th, as instructed) 
I don't even know what's wrong with it anymore

**Comment by onlaj** [comment]
Can you show us some photos of wiring?

**Comment by JustTomMcGee** [comment]
![08D6B63D-F86A-4268-B9EB-56C025CE55F0](https://user-images.githubusercontent.com/81968876/119683843-f9246200-be7e-11eb-8f0f-0f5664211514.jpeg)
![3EBC555D-92E7-4B38-96A3-0272ACB5C40F](https://user-images.githubusercontent.com/81968876/119683889-04778d80-be7f-11eb-8b05-78e80b3fb1c3.jpeg)

**Comment by Rhynden** [comment]
Do you still need help? 
Seems you haven't connected the 5V input to the bottom leftmost pin in your first picture.
So you need another cable connecting the + from the adapter to the bottom leftmost pin.
