### ISSUE TITLE
Can't navigate through the menu and LEDs don't work

### ISSUE THREAD

**Issue by Stefan97a** [onlaj/Piano-LED-Visualizer#225]
![IMG_20210430_200217](https://user-images.githubusercontent.com/83517185/116794700-540ca880-aacf-11eb-9c9c-ca31e4908b01.jpg)

I can't navigate through the menu. I tried to write the file again on the SD card, still the same problem. Does anyone know how to fix this?

**Comment by onlaj** [comment]
Hello.
Does the led strip works?
If not, connect to your RPi with ssh (or connect HDMI to monitor if you can), kill the script with

>sudo pkill python3

navigate to visualizer.py folder,

>cd /home/script

run visualizer

>sudo python3 visualizer.py

and show me the output.

If there are no errors, download [demo ](https://www.waveshare.com/wiki/File:1.44inch-LCD-HAT-All-Code.7z) code for Waveshare screen, unzip, go to RaspberryPi folder and copy paste Python folder somewhere to your RPi, for example to /home/ catalog. 

Then run the key_demo.py with
>sudo python key_demo.py

When demo code is running you can try to press keys, their corresponding names should appear in the console.

**Comment by Stefan97a** [comment]
Hello, the LED strip worked at the beginning. After I clicked on reboot in the menu it didn't work anymore and the screen kept being white. The next day I turned the Rpi on and it was stuck in the menu where I can't navigate.

**Comment by bobsmith1950** [comment]
you need to do the demo test that onlaj posted above - it could just be the waveshare hat playing up rather than a code issue.

**Comment by Stefan97a** [comment]
I can't connect my Rpi with ssh, it just doesn't show up with the IP address. Would a new SD card maybe be a solution?

**Comment by Stefan97a** [comment]
![IMG_20210506_191037](https://user-images.githubusercontent.com/83517185/117349131-55f9b180-aeab-11eb-9f30-0a3e7d95ce81.jpg)

Now I tried it with a new SD card, still the same problem. When it turns on, there is like 1 second before it clicks by itself and then I can't navigate.
If I try the LED strip without the LCD hat, it doesn't work. Could it be the Rpi?

**Comment by bobsmith1950** [comment]
can you plug the pi into a monitor and maybe hook up a usb keyboard to it? then you can test the rpi directly.

**Comment by Stefan97a** [comment]
![IMG_20210513_145929](https://user-images.githubusercontent.com/83517185/118128969-dcf2e080-b3fb-11eb-86de-44f23a685d8f.jpg)

I connect the Rpi to the monitor and put in your commands

**Comment by onlaj** [comment]
My bad, I had wrong command copied.
Instead of
`cd /home/script`

use
`cd /home/Piano-LED-Visualizer`

But from your screenshot I can see that script doesn't return any errors, so try to run demo file.

**Comment by Stefan97a** [comment]
![IMG_20210513_174854](https://user-images.githubusercontent.com/83517185/118151132-93ae8b00-b413-11eb-9979-d74b6115c6ab.jpg)

Now I get this and nothing happens when I press the keys on the piano

**Comment by onlaj** [comment]
It shouldn't, you are suppose to check if the screen's keys are working.
Did you download and upload demo files to your RPi?

**Comment by Stefan97a** [comment]
I uploaded the demo files to the Rpi.
No reaction from the screen keys

**Comment by onlaj** [comment]
So I assume that either the pins on the raspberry pi are damaged or the screen itself.

**Comment by Stefan97a** [comment]
I think it might be the Rpi then, because before it gets stuck in the menu, I can navigate for a short moment. The LED should at least work without the LCD hat right?

**Comment by Stefan97a** [comment]
I bought a new Rpi and now I can navigate through the menu again and also control the LED animations. But now my problem is that the LEDs don't react to the keys on the piano
