### ISSUE TITLE
Is this return normal after booting up the pi with the Visualizer.py code in /etc/profiles?

### ISSUE THREAD

**Issue by Logan-Orr** [onlaj/Piano-LED-Visualizer#228]
Is this return after booting up the pi normal? What concerns me is the import error, is this because I have not connected the Piano or LEDS?
<img width="560" alt="Screen Shot 2021-06-03 at 3 27 54 PM" src="https://user-images.githubusercontent.com/77374951/120720268-a2bbb280-c480-11eb-93e6-eb4643304b9e.png">

**Comment by Logan-Orr** [comment]
And as I press enter, it says this under it,

[1]+  Exit 1                  sudo python3 /home/Piano-LED-Visualizer/visualizer.py

**Comment by onlaj** [comment]
You probably installed wrong version of mido. 
Did you use `sudo pip3 install -r requirements.txt` command?
Did it work earlier? I need more information on that.

**Comment by Logan-Orr** [comment]
Well, if i use the command you gave me, it just returns that i already have the package

This did not work earlier, even if I run the code manually, it says the same thing

**Comment by Logan-Orr** [comment]
By the way, I am using a raspberry pi 4

**Comment by Logan-Orr** [comment]
It says that all the packages are updated and satisfied

**Comment by Logan-Orr** [comment]
Was I supposed to use that command? I did not see it in the manual installation page

**Comment by onlaj** [comment]
I assume you are using system image from [releases](https://github.com/onlaj/Piano-LED-Visualizer/releases)?

**Comment by Logan-Orr** [comment]
No, i used manual installation

**Comment by Logan-Orr** [comment]
Now i get this 
![F9AA0A8C-F69E-4A2A-9609-DDFD9CED6616](https://user-images.githubusercontent.com/77374951/120866063-0fe44c00-c544-11eb-829a-357d04a79d97.png)

**Comment by Logan-Orr** [comment]
What do I do now?

**Comment by onlaj** [comment]
Now it seems there is a problem with rpi_ws281x package, maybe it's damaged, try 
`sudo pip3 uninstall rpi-ws281x`
`sudo pip3 install rpi-ws281x`

you can try to reinstall all packages, just to be sure
`sudo pip uninstall -r requirements.txt -y`
`sudo pip3 install -r requirements.txt`

**Comment by Logan-Orr** [comment]
Ok, heres what i got
After uninstalling and installing
![Uploading E04438E9-5648-405D-8D0E-D01656D3D79C.png…]()

**Comment by Logan-Orr** [comment]
![A5C29B93-7FFD-4958-9BC0-C4BE5B38C3D8](https://user-images.githubusercontent.com/77374951/120867371-a154bd80-c546-11eb-91b1-f1faf4699307.png)

**Comment by onlaj** [comment]
Did you install only rpi-ws281x package or all of them?
If reinstalling all of them doesn't help I would try to start everything from scratch. Maybe use release image?

**Comment by Logan-Orr** [comment]
All of them

**Comment by Logan-Orr** [comment]
But i want to acsess ssh through it

**Comment by Logan-Orr** [comment]
I dont belive you can do that on the realse image

**Comment by Logan-Orr** [comment]
If you can, please send me the link to the dowload

**Comment by onlaj** [comment]
You can https://github.com/onlaj/Piano-LED-Visualizer/releases/tag/v1.00

**Comment by Logan-Orr** [comment]
If I try to use the one in realeses, the zip file is so big that you cant unzip it

**Comment by Logan-Orr** [comment]
So what should I do

**Comment by Logan-Orr** [comment]
Cause i use macos

**Comment by onlaj** [comment]
It's only 2.4GB after unzipping.

> Can you use the one from source forge?

I didn't make that one, so I can't vouch for it.

**Comment by Logan-Orr** [comment]
But if gives me error 79 inappropriate file type or format on yours

**Comment by Logan-Orr** [comment]
Can you give me the standalone img file unzipped?

**Comment by Logan-Orr** [comment]
Or like a google drive download link

**Comment by onlaj** [comment]
Unzipping works on windows and linux, I didn't test it on macos, I don't have any apple products.
I can unzip and host uncompressed version somewhere, but not today, I need several hours.

**Comment by Logan-Orr** [comment]
So, what should i do

**Comment by Logan-Orr** [comment]
Hmmm

**Comment by Logan-Orr** [comment]
Is there a software i could use?

**Comment by onlaj** [comment]
I don't know, as I said, I don't have any apple products.

**Comment by Logan-Orr** [comment]
Ok, got it, Download WinZip for mac then unzip the file, after that drag the imp file to your downloads and you have the imp file, I would edit the repo page so others don't have this problem

**Comment by Logan-Orr** [comment]
how do I ssh into it

**Comment by onlaj** [comment]
The same way you ssh into your own image.
