### ISSUE TITLE
Cant adjust any setting that uses the number selector

### ISSUE THREAD

**Issue by jadenzaleski** [onlaj/Piano-LED-Visualizer#229]
When I try to adjust the start delay or set the RGB value of the LEDs it automatically counts down and does not let me use the joystick to adjust the value. This happens with all number selector settings. Any ideas?

**Comment by onlaj** [comment]
Hey, check your wiring and connection to the screen. Another reason could be a broken button. 
You can try to run a demo file, I explained how [here](https://github.com/onlaj/Piano-LED-Visualizer/issues/225#issuecomment-830694676)

**Comment by jadenzaleski** [comment]
I have updated the visualizer and it seems to be working properly now
