### ISSUE TITLE
Visualizer.py AttributeError

### ISSUE THREAD

**Issue by Hicershice** [onlaj/Piano-LED-Visualizer#24]
Hi,
If i run The Visualizer.py file, this is what it says:

File "visualizer.py", line 1059, in <module> screensaver()
File "visualizer.py", line 714, in screensaver midiports.inport.poll()
AtteibuteError: MidiPorts instance has no attribute 'inport'

Does anyone know what could solve the problem?
In Visualizer.py the class MidiPorts() has 'self.inport' so it has to work I think. I just can't help myself .
I tried three times to completely reinstall the RPi and start with this guide from scratch but I fail Everytime at this point

**Comment by Hicershice** [comment]
Is it possible that this happens because I dont have anything connected? is "inport" the incoming signal from the keyboard?

**Comment by onlaj** [comment]
Yes, this is because no keyboard is attached. I will edit the code so it won't crash when starting screensaver.

**Comment by Hicershice** [comment]
Thank you very much !
