### ISSUE TITLE
Flask

### ISSUE THREAD

**Issue by Logan-Orr** [onlaj/Piano-LED-Visualizer#243]
So, this project has been working fine, but one day i turned it on and it did not boot, it was stuck at the white screen, I reinstalled the software, it worked. But, I still had to update it, I updated it and tried to boot it, same thing. Did not work. I was able to ssh into it and it said the it was missing something called Flask, I did not do anything to the software in any way that would make it stop working, please help.

Here is the error after updating: 
![C84572F7-4C56-4E98-AC14-FD24BDEAAD2D](https://user-images.githubusercontent.com/77374951/128746720-9dd707fe-9fd3-49da-b4fa-762e0a867a6b.png)

**Comment by onlaj** [comment]
Hello.
Sorry for this inconvience, but in latest updates I added a lot of new features which requires additional libraries. You can install them using command:

`sudo pip3 install -r requirements.txt`

**Comment by Logan-Orr** [comment]
Do I reinstalled then do this, cause it gives me this error
![CCB49047-3EF8-432A-B616-7B0EA0FCDDD7](https://user-images.githubusercontent.com/77374951/128751998-b083a695-4390-44d8-8c86-203aaf758394.png)

**Comment by onlaj** [comment]
You need to be in visualizer directory

`cd /home/Piano-LED-Visualizer/`

**Comment by Logan-Orr** [comment]
Ok

**Comment by Logan-Orr** [comment]
Now this;
![Uploading 55F10104-3471-47E0-93F5-03971022B51B.png…]()

**Comment by Logan-Orr** [comment]
![7BD4E19B-5A71-4FC0-8E94-93B8B2329940](https://user-images.githubusercontent.com/77374951/128752708-0aac2d74-97d2-43fd-8f81-7bfdd1719717.png)

**Comment by Logan-Orr** [comment]
Maybe I installed the wrong version?

**Comment by Logan-Orr** [comment]
Should I try to restart?

**Comment by onlaj** [comment]
What did it show after `sudo pip3 install -r requirements.txt`?

**Comment by Logan-Orr** [comment]
It installed everything, no error

**Comment by Logan-Orr** [comment]
Including flask

**Comment by onlaj** [comment]
Try to restart then, you can check installed packages with
`pip3 list`

**Comment by Logan-Orr** [comment]
Like reintall and stuff

**Comment by onlaj** [comment]
For now just restart RPi, I doubt it will help but it's worth a try

**Comment by Logan-Orr** [comment]
K

**Comment by Logan-Orr** [comment]
Yeah did not work

**Comment by Logan-Orr** [comment]
Would this mean that it will not work for everyone else?

**Comment by onlaj** [comment]
Works for me, other users also tested latest update and no one reported problems with importing flask module.

I will soon make new release with everything configured.

**Comment by Logan-Orr** [comment]
Should I re download the image of the github page and use that have you updated the image recently

**Comment by onlaj** [comment]
No, image is not updated.
btw. try to 
`sudo pkill python3`
before launching new script. When you ssh it autostart script, maybe you have moer scripts running and it can cause some problems.

**Comment by Logan-Orr** [comment]
Where am I supposed ptut this

**Comment by Logan-Orr** [comment]
You can just tell me the exact instructions or walkthrough of this like what commands to enter and when

**Comment by onlaj** [comment]
SSH to your RPi, then go into visualizer directory
`cd /home/Piano-LED-Visualizer/`

stop all python scripts, just in case
`sudo pkill python3`

start script
`sudo python3 /home/Piano-LED-Visualizer/visualizer.py`

**Comment by Logan-Orr** [comment]
Did not work

**Comment by onlaj** [comment]
What does it show? Still the same error?

**Comment by Logan-Orr** [comment]
same error

**Comment by Logan-Orr** [comment]
I just installed a fresh software and its booted, and still on the old version, so no learn midi etc

**Comment by Logan-Orr** [comment]
what do I do now

**Comment by onlaj** [comment]
Well, I can only recommend that you reinstall everything (maybe try to follow manual setup?) or wait till I release new image.

I'd like to finish the webinterface first tho; hopefully, I'll be able to do it this week.

**Comment by Logan-Orr** [comment]
I GOT IT, what you have to do is run `sudo pip3 install Flask` before you update, and then right after you update, you have to install the requirements again before you reboot

**Comment by Logan-Orr** [comment]
oh and the web interface is cool! Keep working on it
