### ISSUE TITLE
Bluetooth synthesia randomly working

### ISSUE THREAD

**Issue by DjangoPiano** [onlaj/Piano-LED-Visualizer#247]
Hi, 
I was interested in using Synthesia with the PLV device. Here is the problem : I connect my computer to the RPI by bluetooth, I open Synthesia by holding shift key to put the RT midi on, but when Synthesia opens, I really struggle to find my device in the settings. It works like once in ten.
Any ideas to have it working properly ?

Thank you very much for your help, I appreciate your work.

**Comment by onlaj** [comment]
Hey, I do not recommend using bluetooth as a connection between your Synthesia's device and RPi. Use RTP MIDI instead.

**Comment by DjangoPiano** [comment]
Hi,
Thank you for your answer. Could you please give me some details about RTP
MIDI ? How does it work ?

Thanks for your work.

**Comment by onlaj** [comment]
https://github.com/onlaj/Piano-LED-Visualizer#learning-to-play-with-synthesia
