### ISSUE TITLE
[Question/Enhancement] USB to Host support? 

### ISSUE THREAD

**Issue by DeckerExpert** [onlaj/Piano-LED-Visualizer#252]
I have a Yamaha P-45 and I wish to add the LED visualizer to it. However, the digital piano has USB to Host instead of MIDI to USB. Will this still work?

**Comment by onlaj** [comment]
Yep, you connect your piano to RPi directly with usb cable.

**Comment by DeckerExpert** [comment]
Oh phew! I'll update this issue if anything goes wrong. Thank you for the fast response!
