### ISSUE TITLE
I'm a very newbie. Help me plz..

### ISSUE THREAD

**Issue by songazi123** [onlaj/Piano-LED-Visualizer#253]
There was an extra raspberry pie 3B left in my house, and I proceeded with it, But it didn't work at all. (If Raspberry Pie Zero WH is absolutely necessary, I will repurchase it.)
I tried manual installation too, but I failed because I'm a beginner.
I think this problem has occurred because I connected the wrong wire or did not solder.
And I don't have a 1.4 inch LCD.(If this is necessary to proceed with the project, I will get it. / I just need the LED function to react when I press the piano.)
I'd really appreciate it if you could help me with my problem. (I am sorry that I am not good at English :) 
![KakaoTalk_20210902_221300945](https://user-images.githubusercontent.com/89983467/131849924-0e67005f-43e4-4134-941c-04559c4c51e9.jpg)
![KakaoTalk_20210902_221256415](https://user-images.githubusercontent.com/89983467/131849929-0e7a4de8-58e2-471c-bc6c-247865ac2d81.jpg)
![KakaoTalk_20210902_221256415_01](https://user-images.githubusercontent.com/89983467/131849933-692243ac-6b8e-421a-baaa-1db2d500c833.jpg)
)

**Comment by onlaj** [comment]
Hey.
Your wiring looks wrong, check this site: https://tutorials-raspberrypi.com/connect-control-raspberry-pi-ws2812-rgb-led-strips/
There are 5 cables coming from led strip but in this setup we only use red green and white set, you can ignore the red and white two-cables set.

**Comment by songazi123** [comment]
black and green wire is 7inch LCD display's one. I connected the two lines of the LED strip to GPIO18 and GND, and the + pole to the DC socket.
![KakaoTalk_20210903_090132253](https://user-images.githubusercontent.com/89983467/131930851-c9c32dec-ae92-4601-9db1-ae50f36bad6a.jpg)
I also noticed that LED strips were occasionally briefly lit by about a fifth. (or just one last LED).

**Comment by onlaj** [comment]
GND should be connected both to RPI and led strip, you need to put led strip's GND wire to socket.
