### ISSUE TITLE
Synthesia android RTP connection

### ISSUE THREAD

**Issue by bradliegek3** [onlaj/Piano-LED-Visualizer#259]
Hi,

I am trying to get synthesia to work on my android with touchdaw. No matter what port I choose in touchdaw, I can't find the rpi in synthesia. Do you have a step by step tutorial on connecting the rpi to synthesia with wifi?

**Comment by Orly1625** [comment]
Not use that, the best is use the Sevilla soft midi de ice, i use and work perfect

**Comment by AbrahamWisman** [comment]
@bradliegek3 try the app "midi connector", its on the play store.
