### ISSUE TITLE
The led light does not align with some keys

### ISSUE THREAD

**Issue by Joker-rider** [onlaj/Piano-LED-Visualizer#270]
Hi guys,
Is there a way to adjust the separation between the leds to line them up with the keys? I have a little problem where as the keys go down or up the light alignment drifts. The central C and a few other keys are perfectly aligned.
My 76-key keyboard. Config origin.
I tried to adjust with the web interface but apart from moving the leds and my central C nothing changes.
Impossible to say that when I reach a certain key the led on changes.
Example: C = do = LED 72 + 8 = OK
Coming down :
Note D# (Re #) = LED 63 = OK, (Re #) = LED 39 = KO => LED 40 = OK.
And amount
Note B (if)(si) = LED 72 + 30 = KO => LED 72 + 29 = OK
![16362221212827683533777697058386](https://user-images.githubusercontent.com/93837055/140619606-f99c99db-8b5a-41ed-bcf5-4ca4b81129ce.jpg)
![16362222367564817665638788167103](https://user-images.githubusercontent.com/93837055/140619648-cc879fdb-9ccf-47cf-9e2c-4e4af58d7b41.jpg)

For information i'm french

Thank you for your help

**Comment by onlaj** [comment]
Hello.
It seems unusual, I wonder if the reason is the non-standard width of the piano keys or maybe a different model of the led strip.
I will try to make some option to adjust spacing, but for now you can try to fix it by yourself. The function that is responsible for that is located in [/lib/functions.py](https://github.com/onlaj/Piano-LED-Visualizer/blob/master/lib/functions.py) under 

```
def get_note_position(note, ledstrip):
    if note > 92:
        note_offset = 2
    elif note > 55:
        note_offset = 1
    else:
        note_offset = 0
```

It means that for notes higher than 92 the offset it equal to 2, and for notes higher than 55 (but lower than 92) it's 1. You can try to adjust those values, change 92 to something lower like 72, and 55 to 35, you need to test it by yourself.

**Comment by Joker-rider** [comment]
Hello
Thanks
I will test the solution tonight and give tout a feedback.

**Comment by Joker-rider** [comment]
Hello.
Is there a possibility of being able to carry out several offset?
Example : one in note 92, one in note 72, one in note 55 and one in note 35?

**Comment by Joker-rider** [comment]
Hello
is there a test mode to light all the leds corresponding to the keyboard notes in order to best place the led strip. the ideal would be to be able to make the adjustments directly with the leds on (number of keys = leds, offset settings in order to correct the drifts ...)

I am still in settings mode to align the leds on my keys.

Bye

**Comment by Joker-rider** [comment]
Hello Onlaj,
I would like to know if it is possible to letter more than two offsets (example 4 offsets)?

**Comment by onlaj** [comment]
Yes, just edit the code accordingly.

for example:

```
def get_note_position(note, ledstrip):
    if note > 92:
        note_offset = 3
    elif note > 55:
        note_offset = 2
    elif note > 35:
        note_offset = 1
    else:
        note_offset = 0
```

**Comment by Joker-rider** [comment]
Hello Onlaj
Have you other solution ?

**Comment by onlaj** [comment]
Can you show me how you edited the "get_note_position" function? Screenshot of your text editor will be fine.

**Comment by Joker-rider** [comment]
Hello,
here is the screenshot
![IMG_20211118_222159](https://user-images.githubusercontent.com/93837055/142683730-d0e2cbb6-4729-473c-92f7-795cb4d15f32.jpg)

**Comment by Joker-rider** [comment]
Hello
here is the screenshot

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Joker-rider** [comment]
Hello Onlaj
do you have solution to my problem ?
Thank you so much

**Comment by onlaj** [comment]
Sorry, somehow I missed last response.
Can you launch visualizer (with your changes) manually?

`sudo python3 /home/Piano-LED-Visualizer/visualizer.py`

if it crash post an error message here.

**Comment by Joker-rider** [comment]
here is the test
![Uploading IMG_20211122_212453.jpg…]()

**Comment by Joker-rider** [comment]
Heure is the test
![Uploading IMG_20211122_212453.jpg…]()

**Comment by Joker-rider** [comment]
Here is the test.
![IMG_20211122_212453](https://user-images.githubusercontent.com/93837055/142931336-7906c9c1-8409-4427-8ec2-c68b69a14a41.jpg)

**Comment by onlaj** [comment]
Did you copy the code from [here](https://github.com/onlaj/Piano-LED-Visualizer/issues/270#issuecomment-968690075) or retype it by yourself? 
When editing code, use 4 spaces instead of tabs.

**Comment by Joker-rider** [comment]
I used 4 spaces instead of tabs and it worked.
Perfect.
Thank you so much.
