### ISSUE TITLE
Address already in use? 

### ISSUE THREAD

**Issue by AlexMosley** [onlaj/Piano-LED-Visualizer#271]
Hi there, I've gone through everything in the readme and now every time I reboot I get the attached error saying that the address is already in use. How can I fix this? Thanks! 
![20211108_212852](https://user-images.githubusercontent.com/52784777/140852319-d0cddf1a-8db9-462c-b2bc-956e21163468.jpg)

**Comment by onlaj** [comment]
Hello.
It seems that something on your RPi or network is already using port 8080 (needed for the web interface).
You can set a custom port number by adding a parameter

`sudo python3 /home/Piano-LED-Visualizer/visualizer.py --port 5000`

You'll also have to edit the crontab command.
