### ISSUE TITLE
Request: Random color led 

### ISSUE THREAD

**Issue by Caioalcantaraa** [onlaj/Piano-LED-Visualizer#272]
First, I would like to thank you for your work.

Would it be possible to create an animation to light colors randomly on the leds?

**Comment by onlaj** [comment]
Hello.
Can you elaborate? What should it look like?
And do you mean animation on idle or when you play?

**Comment by Caioalcantaraa** [comment]
Hi,
I have a video demonstrating how it works:
https://youtube.com/shorts/rR9g6TaUXVc?feature=share

I used a code but it was from Arduino, I'll post the link to which file I used:
Vídeo: https://youtu.be/kAj78IE2704

Arquive “random colora”: https://github.com/roy-sukrit/Arduino-LED-Piano

**Comment by onlaj** [comment]
Set color to rainbow, scale and timeshift to 1000 and you have random colors :D
