### ISSUE TITLE
Visualizer does not run after last update

### ISSUE THREAD

**Issue by EFeru** [onlaj/Piano-LED-Visualizer#280]
Hi Onlaj,

I just updated the Visualizer to the most recent version, did everything, RPi0 update, upgrade, Visualizer reinstall of requirements, reboot. But I still get the error in the picture. Any idea?
![Screenshot_20211119-181455](https://user-images.githubusercontent.com/24780745/142664346-7724d3a2-7ef6-43ca-9d0a-b3baf0537ecd.jpg)

**Comment by onlaj** [comment]
Hello.
I will fix it in next update, for now follow this part of manual: https://github.com/onlaj/Piano-LED-Visualizer/blob/master/Docs/manual_installation.md#2-creating-autoconnect-script

**Comment by EFeru** [comment]
It worked! Even though the midi.service file does not exist or I couldn't create it in my case. But it works even without.

Awesome job on the webinterface! I like it very much! Thanks
