### ISSUE TITLE
led visualizer & daw

### ISSUE THREAD

**Issue by darmap** [onlaj/Piano-LED-Visualizer#281]
when using the led visualizer, can I still connect the piano to the daw on my computer?

**Comment by onlaj** [comment]
Yes
https://github.com/onlaj/Piano-LED-Visualizer#learning-to-play-with-synthesia

**Comment by darmap** [comment]
> Ya https://github.com/onlaj/Piano-LED-Visualizer#learning-to-play-with-synthesia

and why when i connect the raspberry to wifi the ssh and wpa_supplicant files disappear from the micro sd?

**Comment by onlaj** [comment]
I don't know the details, but those files are loaded once and then deleted,. Wifi pass is saved tho and it should connect to your router.
