### ISSUE TITLE
What is the difference between Multicolor vs. Rainbow?

### ISSUE THREAD

**Issue by clancel** [onlaj/Piano-LED-Visualizer#290]
I noticed that the colors on the led strip for both Multicolor and Rainbow options on the Visualizer Menu are the same.  Is there any difference?  I would like to be able to assign colors of my choosing to keys when pressed.  Is this possilble?

**Comment by onlaj** [comment]
Hey.
They are not the same. In multicolor mode you can set a color for a range of keys. In rainbow mode it loops through all colors along the keyboard.
