### ISSUE TITLE
Program unexpectedly freezes

### ISSUE THREAD

**Issue by MrBromaba** [onlaj/Piano-LED-Visualizer#3]
Hi, so I have noticed that sometimes while I play the program seems to crash, the LEDs won't light up anymore and the LEDs pressed at the moment of crash stay on. Sometimes this takes a while to kick in but sometimes it happens almost immediately after running the program... any ideas why this happens?

**Comment by onlaj** [comment]
What does the console say?

**Comment by MrBromaba** [comment]
Actually, nothing. It looks like everything is running well although it doesn't work.

**Comment by onlaj** [comment]
Do you have screen connected? Is the menu still working?

**Comment by MrBromaba** [comment]
Hi, sorry for the late response. I don't use the display yet as I'm only using the lioghtkeys.py file and I control the Pi with a SSH client. Seems like the problem isn't coming from your code but rather from the Raspi, I sometimes the green LED in goes off and then the LED strip freezes. Hasn't happened in the past couple of days...
