### ISSUE TITLE
Detailed wiring / connectors / wires explanation?

### ISSUE THREAD

**Issue by ZoeESummers** [onlaj/Piano-LED-Visualizer#30]
I'd very much like to make this project for myself and for someone else. 

However, whilst I can understand the software side, I've never done any soldering or wiring before and neither this nor the reference article go into any detail on how to actually make this up, what type of wiring to use, what type of connectors are required, and how / where to create or solder custom wires. 

The closest is a poor graphic showing a splitter wire, but none - as far as google / Ebay searches have demonstrated - can be found. 

Is there some way to get more explicit hardware instructions and part list? I'm not interested in breadboards and pin connectors - this needs to be solid for a non-technical person to own / use. 

Thanks

**Comment by onlaj** [comment]
Hello.
As for wires I suggest something like this https://amzn.to/2m81MEf , diameter should be around 1mm (18 Gauge or 0.04 inch in US system). Try to find something cheaper if you don't need cables that long.
This project doesn't require any soldering unless you want to make it really sturdy, for me using heat shrink bands is enough.
