### ISSUE TITLE
PI ZERO 2 Error 

### ISSUE THREAD

**Issue by LemonHK32** [onlaj/Piano-LED-Visualizer#304]
When i open the visualizer.py it said

Traceback (most recent call last):
  File "visualizer.py", line 1, in <module>
    import webcolors as wc
ImportError: No module named webcolors

i checked all the issues and file 
I spend 3 day on it already can someone help me

**Comment by onlaj** [comment]
Hello.
Did you install all requirements?

The command is:
`sudo pip3 install -r requirements.txt`
