### ISSUE TITLE
LCD 3.5"

### ISSUE THREAD

**Issue by Shahroozgr** [onlaj/Piano-LED-Visualizer#31]
Hi 
Is it possible to use 3.5" SPI TFT LCD?

**Comment by onlaj** [comment]
Hello.
Unfortunately it will only work with Waveshare LCD TFT 1,44'' 128x128px, if you want to make it work with other screens you would have to edit whole MenuLCD class.

**Comment by Shahroozgr** [comment]
ohh
thanks
