### ISSUE TITLE
Cannot connect through RTPmidi anymore

### ISSUE THREAD

**Issue by tanhongoc96** [onlaj/Piano-LED-Visualizer#313]
Hello, I am a newbie,
I have tried to connect through RTPmidi port and it has worked before. 
Today, when I try to connect through RTPmidi port again it shows the error: 
"2600:1700:2094:3400:c0b9:ab51:8ac1:c1d1:53878 didn’t respond to the connection request. Check the address and port, and any firewall or router settings. (16:59:48)"
I do not change the router or any firewall setting, not sure why this happened, but I still can control the led strip effects through the web interface, but the key light function does not work anymore.

**Comment by AL1-1956** [comment]
Hello tanhongoc96 the RTPmidi uses ethernet protocol to communicate.
So 2600:1700:2094:3400:c0b9:ab51:8ac1:c1d1:53878 is the IP V6 address of the device (either you Pi or your PC)
When you switch off an on a device connected on a network (either via Wifi or via Ethernet Cable) it may or may not get the same IP address as the last time (It's called DHCP (Dynamic Host Configuration Protocol).
So if your previous RTP session was between 2 devices and one (or both) of the device(s) has changed his IP Address the RTP does not work anymore.
You can check on your PC with the command "ipconfig" in a DOS Box and on your Pi with the command "ifconfig" in a shell window.
If the adress 2600:1700:2094:3400:c0b9:ab51:8ac1:c1d1:53878 is not found , you have the cause of your problem.
I do not use RTP so I do not know how to reinit the whole thing .... Sorry
