### ISSUE TITLE
Some LCD screen error for the visualizer.py

### ISSUE THREAD

**Issue by omidfk** [onlaj/Piano-LED-Visualizer#32]
SPI is enable,but I execute the the command sudo -E python visualizer.py, I got following error.

Traceback (most recent call last):
File "visualizer.py", line 3, in
import LCD_1in44
File "/home/pi/Desktop/pianoled/LCD_1in44.py", line 28, in
import LCD_Config
File "/home/pi/Desktop/pianoled/LCD_Config.py", line 38, in
SPI = spidev.SpiDev(0, 0)
IOError: [Errno 2] No such file or directory

**Comment by donwatermelon** [comment]
Hi omidfk, I've got almost exactly the same error and noticed you closed the issue. Did you resolve the problem and if so, could you share your fix? It's been bugging me for the last day.

Thanks in advance.
