### ISSUE TITLE
Visualizer.py AttributeError

### ISSUE THREAD

**Issue by omidfk** [onlaj/Piano-LED-Visualizer#33]
Hi,
If i run The Visualizer.py file, this is what it says:

Traceback (most recent call last):
  File "visualizer.py", line 1061, in <module>
    screensaver()    
  File "visualizer.py", line 746, in screensaver
    if (midiports.inport.poll() != None):
AttributeError: MidiPorts instance has no attribute 'inport'

Does anyone know what could solve the problem?

**Comment by onlaj** [comment]
Hello.
You don't have your piano connected to RPi, right?
In next update I will add an exception which will prevent this error even if you don't have keyboard.

**Comment by omidfk** [comment]
Thank you very much
