### ISSUE TITLE
Add feature to predict next led on learning mode

### ISSUE THREAD

**Issue by theblackhat17** [onlaj/Piano-LED-Visualizer#335]
Hi Onlaj, I'm still progressing perfectly well in the project, and I just had an idea, do you think it would be possible to improve the learning function of a song by making the led strip display the next led in addition to the current one, why not in another color and using a fade in? The goal is to predict the next led so that the user can have an idea of the next one.
Tell me if this is easy to do or possible ;)
Thank you!
Clément

**Comment by onlaj** [comment]
Hey, it took a while, but I've implemented something similar to what you requested. You can find the changes here:
https://github.com/onlaj/Piano-LED-Visualizer/tree/learn_enhancement

I will perform some additional tests to ensure everything works smoothly before merging it into the main branch.
