### ISSUE TITLE
 Error during program execution

### ISSUE THREAD

**Issue by theblackhat17** [onlaj/Piano-LED-Visualizer#336]
Hello Onlaj, do you know why when I run the save function, the program gives me an error in the terminal?
![273924404_959350864712055_4513704510512589815_n](https://user-images.githubusercontent.com/69344806/156226114-c6e5d147-63d9-4496-8f5c-be5e04ca4eaa.jpg)

**Comment by onlaj** [comment]
Hello, sorry for late response.
Does it happen everytime you try to save recording?
Try to delete whole script and clone it again.

```
cd /home
sudo rm -rf Piano-LED-Visualizer
sudo git clone https://github.com/onlaj/Piano-LED-Visualizer
```
