### ISSUE TITLE
LED Colors are not right

### ISSUE THREAD

**Issue by ghost** [onlaj/Piano-LED-Visualizer#337]
Hello,

Thanks for the Piano LED Visualizer. It is great but I have an issue with colors.

I set the backlight to 30% red, and the LED Strip mixed up the colors. I had the same Issue, when I run the example code from Adafruit ([Link](https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage))  I changed `ORDER = neopixel.GRB` to `ORDER = neopixel.RGBW` and I uncommend/commend the corresponding parts in the end and it worked.

How can I change this in the Visualizer to solve the problem?

![Bildschirmfoto 2022-03-04 um 09 41 18](https://user-images.githubusercontent.com/62639464/156737502-c2978eed-2403-4ca7-970a-1e09f3574fd0.png)
![Unknown](https://user-images.githubusercontent.com/62639464/156737515-c57f5dd4-808c-419c-8212-819f805e7842.jpeg)

**Comment by onlaj** [comment]
Hello.
What is the name of this led strip? SK6812?

**Comment by Ferdinandehni** [comment]
Oh no. You are right, it is an SK6812RGBW. I bought the parts not carefully enough.
