### ISSUE TITLE
Attribute Error while running visualizer.py

### ISSUE THREAD

**Issue by hillowner45** [onlaj/Piano-LED-Visualizer#35]
Hey man I'm running into this error when running visualizer.py

File "/home/pi/.local/lib/python2.7/site-packages/mido/backends/rtmidi.py", line 34, in _get_api_id return rtmidi.API_UNSPECIFIED
AttributeError: 'module' object has no attribute 'API_UNSPECIFIED"

I've uninstalled any variants of python-rtmidi like rtmidi_python and rtmidi but am still running into the error

Thank you!

**Comment by onlaj** [comment]
Someone had similar problem here https://github.com/mido/mido/issues/152
Try to uninstall every rtmidi you installed and then install the right one.
```
pip uninstall rtmidi
pip uninstall python-rtmidi
pip install python-rtmidi
```
