### ISSUE TITLE
Animated Backlight [enhancement]

### ISSUE THREAD

**Issue by Nbobito** [onlaj/Piano-LED-Visualizer#356]
What if the backlight could have animations on it? That way, you can play with animations simultaneously, and they could be dimmed like the regular backlight. It could be set in the backlight color menu, under the category "backlight with animations," in case more special backlight colorings/features get added in the future.

**Comment by onlaj** [comment]
[Done](https://github.com/onlaj/Piano-LED-Visualizer/pull/411)
