### ISSUE TITLE
No different colors for left and right hand while playing with Synthesia

### ISSUE THREAD

**Issue by Sonar10** [onlaj/Piano-LED-Visualizer#357]
Hello,
I have a problem, when I try to learn to play with Synthesia, my LEDs don't indicate the color of corresponding hand (blue, green), all LEDs light in white. I tried different configuration but without success. I have connections like this: RPi->USB OTG-> Piano and RPi->USB OTG->Sevilla's Soft MIDI USB-USB->PC

Could you help me?

**Comment by onlaj** [comment]
Hello.
Did you change your Synthesia's settings to "Finger-based channel"? It's under MIDI USB-USB output -> key lights.

**Comment by Sonar10** [comment]
Yes, I did: Music output ->MIDI USB-USB->Key Lights ->Finger-based channel.
I'm sending pictures, because LEDs have weird behaviour.
![01 before pushed](https://user-images.githubusercontent.com/105850891/169265764-2768c00b-8ba4-4291-b91b-83e161fdd5bb.jpg)
![02 pushed keys and hold](https://user-images.githubusercontent.com/105850891/169265784-6864e0d6-c454-4b05-885b-0efb3db0e56d.jpg)
![03 after release](https://user-images.githubusercontent.com/105850891/169265793-d5c20c33-22e4-4f00-a42e-2ef8b82a3c30.jpg)

**Comment by onlaj** [comment]
What about other output settings in Synthesia? Set "my notes" as disabled, same with "prevent local notes".
If it doesn't help, there is a workaround. Go into "Led settings" -> "Skipped notes" and select "normal".

**Comment by Sonar10** [comment]
I did all things that you mentioned above - now LEDs not showing the first notes at all, but if I press them and the next notes are the same they light up properly in blue and green. I'm sending more pics:
![1](https://user-images.githubusercontent.com/105850891/169280172-42859f99-6ba6-44a6-af3c-a1e80efbae82.jpg)
![2](https://user-images.githubusercontent.com/105850891/169280175-99467ad3-ada7-41ee-8369-f421a47cfefc.jpg)
![3](https://user-images.githubusercontent.com/105850891/169280177-8ab984e4-c333-49a2-bc8d-036f29f54336.jpg)
![4](https://user-images.githubusercontent.com/105850891/169280179-659e4425-fc20-41c4-88e8-4e272a63f857.jpg)
![5](https://user-images.githubusercontent.com/105850891/169280181-f12f2492-71f1-4002-894e-a9e1a9e3cac8.jpg)
![leds](https://user-images.githubusercontent.com/105850891/169280182-8fa159e8-6e17-4097-bcc2-360db82d88b4.jpg)

**Comment by onlaj** [comment]
Did you try other midi files? Does the same thing happen with Synthesia's default songs?

**Comment by Sonar10** [comment]
I think you were right. I downloaded some songs and it works good. What I've noticed that not all MIDI files show hands - I assume that the MIDI file must be prepared somehow by creator to indicate hands right? And the second question do you know any good MIDI files repository?

**Comment by onlaj** [comment]
[Musescore](https://musescore.com/) with some browser extension for downloading files.
