### ISSUE TITLE
Feature Request: Colors assigned to notes

### ISSUE THREAD

**Issue by ajayprk** [onlaj/Piano-LED-Visualizer#37]
If possible and feasible, could you please add functionality to set colors for different piano notes. eg. i should be able to set a specific color for all the keys mentioned below so whenever I hit a specific key in any octave, the same color should light up:
C, D(Flat), D, E (Flat), E, F, G (Flat), G, A (Flat), A, B (Flat), B

Thank-you for the consideration

**Comment by onlaj** [comment]
Hello.
I added a requested feature https://github.com/onlaj/Piano-LED-Visualizer/commit/7dda0e331fb916443a1137af1040b1ac551920f1
