### ISSUE TITLE
LED Strip Density Option

### ISSUE THREAD

**Issue by shinkuan** [onlaj/Piano-LED-Visualizer#373]
Hello, this is a really cool project.
Do I must use 144LED/meter LED strip for this to work properly?
Which means there will be 2 LED per Note.
Is there an option where I can set it to 1 per Note?

I'm asking this is because I'm designing LED Strip PCB for this. 1 LED per Note can bring lower power consumption, and lower cost.

**Comment by onlaj** [comment]
Hey, for now it supports only 1 or 3 leds per key press.
You can find code responsible for that [here](https://github.com/onlaj/Piano-LED-Visualizer/blob/master/lib/functions.py#L243)
