### ISSUE TITLE
Does this work with live-input?

### ISSUE THREAD

**Issue by jonas2727** [onlaj/Piano-LED-Visualizer#374]
Is this "only" able to visualize exisiting midi-files or is it possible to visualize live midi input? If so, how much of a delay is there and is it noticable? Thanks in advance.

**Comment by onlaj** [comment]
Hey, did you watch the [video](https://www.youtube.com/watch?v=IZgYViHcXdM)?
You can play and light keys at the same time, delay is not noticable.

**Comment by jonas2727** [comment]
Awesome thanks!
