### ISSUE TITLE
[Enhancement] Log/Event viewer in web interface

### ISSUE THREAD

**Issue by sreich** [onlaj/Piano-LED-Visualizer#378]
Love this project so far and what it's helped me do

My issue is I'm troubleshooting some MIDI event issues and having a midi event viewer inside, perhaps on the Ports/Connections page, would be great.

A simple "[time] read MIDI message yada yada" that updates would be great. Would not even have to be persisted to disk

**Comment by onlaj** [comment]
Hey, something like that will be enough?

![chrome_fUJZosUJjx](https://user-images.githubusercontent.com/9073428/202443563-2f384f0e-7693-4ea9-931f-0039b9024fc8.gif)

**Comment by onlaj** [comment]
Added, you can find new function under "ports" tab on the web interface.
