### ISSUE TITLE
LED Color Accuracy

### ISSUE THREAD

**Issue by ausfalt** [onlaj/Piano-LED-Visualizer#382]
Not too familiar with LED lights but I wanna check if this has something to do with the LED strip or otherwise?

I'm trying to do a yellow color (#FFFF00)  but on the LED, it looking greenish (yellow-green). Same observation from my friends. 

I have attached a screenshot from the web interface:
![Backlight-web visualizer](https://user-images.githubusercontent.com/110845450/188410500-a1b878a2-5309-45a5-89db-7f1f5a690b03.jpg)

**Comment by onlaj** [comment]
Some leds are going into greenish indeed.

![PXL_20220905_090900605](https://user-images.githubusercontent.com/9073428/188413542-66f21fde-9f36-427a-ad7a-ff0d4dcc981e.jpg)

(i swear it's not as dusty as it looks on photo :D)

In my case it was always like this, each led has it's own hue. Maybe more expensive and higher quality led strips are immune to that.
Try to fiddle around with different color values.

**Comment by ausfalt** [comment]
Thanks man. Definitely will adjust based on the actual light instead of the specific color input then. 

Cheers.
