### ISSUE TITLE
ImportError: cannot import name 'safe_join' from 'werkzeug.utils'

### ISSUE THREAD

**Issue by AlexWangFTC** [onlaj/Piano-LED-Visualizer#385]
When installing and running visualizer for the first time while installing all the requirements, I get this error.
![image](https://user-images.githubusercontent.com/23690647/190846267-a56d4e3d-1a9e-49ab-86d6-872e8bb050f9.png)
I cannot uninstall and reinstall another werkzerg version, is there any strategies around this?

**Comment by onlaj** [comment]
Hello, check [this issue](https://github.com/onlaj/Piano-LED-Visualizer/issues/354)

**Comment by AlexWangFTC** [comment]
Thank you so much! This was perfect
