### ISSUE TITLE
Velocity mode 

### ISSUE THREAD

**Issue by Rodrix33333** [onlaj/Piano-LED-Visualizer#390]
The velocity mode lights up correctly the key led; however it fails to correctly light up the side leds. They fade out very quickly and only one led remains lit.

I see the code is affected by control pedal. This might be the issue. How is the pedal supposed to affect this behavior?

What is the pedal "dead zone" in the vars?

I have a continuous pedal controller which outputs different values (half pedalling is supported). If I understand I might be able to help fix a bug.

Thanks for this awesome project. It's incredible 💫🍦

**Comment by onlaj** [comment]
I think I overcomplicated that part. It should be easier to redesign Velocity mode to ignore pedal signal and then add "the pedal keeps the LEDs lit" applicable to all light modes.

**Comment by Rodrix33333** [comment]
I think that's a great idea! I like the new branch proposal.
