### ISSUE TITLE
How to Change Time

### ISSUE THREAD

**Issue by r0bvas** [onlaj/Piano-LED-Visualizer#396]
On Raspberry Pi to local time. If I record midi in raspberry, the files time is different than local time.

**Comment by onlaj** [comment]
Hey,
If RPi is connected to internet it should update the time automaticaly. You can change timezone by typing `sudo raspi-config` in a console, a proper setting should be somewhere in that menu.
If your raspberry is not connected to internet that command should work:

`sudo date -s ‘YYYY-MM-DD HH:MM:SS’`

**Comment by r0bvas** [comment]
Thank you! Greatly appreciated.
