### ISSUE TITLE
Needs automatic port setup for Play_MIDI

### ISSUE THREAD

**Issue by jsm174** [onlaj/Piano-LED-Visualizer#4]
Automatic port setup was added a few days ago in this commit:

https://github.com/onlaj/Piano-LED-Visualizer/commit/5d5df51ed6f1cacc8cb6f80f149d3efb809a582b#diff-20e433b96c154faaedd1c04789627107L609

It would be nice if that could be done when trying to play midi as well:

https://github.com/onlaj/Piano-LED-Visualizer/blob/master/visualizer.py#L369

I'd submit a PR, but I'm a little confused. Was the intent of midi playback to use playport?

```
if(location == "Choose_song"):            
    play_midi(choice, 'mio:mio MIDI 1 20:0')
.
.
.
def play_midi(song_path, port):
    menu.render_message("Playing: ", song_path)
    try:
        mid = mido.MidiFile("Songs/"+song_path)
        port = mido.open_output(port)
        for msg in mid.play():            
            port.send(msg)  
            if GPIO.input(KEY2) == 0:
                break
    except:
        menu.render_message("Can't play this file", "", 2000)
```

vs

```
if(location == "Choose_song"):            
    play_midi(choice)
.
.
.
def play_midi(song_path):
    menu.render_message("Playing: ", song_path)
    try:
        mid = mido.MidiFile("Songs/"+song_path)
        for msg in mid.play():            
            midiports.playport.send(msg)         
            if GPIO.input(KEY2) == 0:
                break
    except:
        menu.render_message("Can't play this file", "", 2000)
```

FWIW, since I'm coming up to speed on MIDI, it would be nice in the docs to have the purpose of `inport`, `outport`, and `playport` -- even if it is just common sense, and I'm being an idiot :)

**Comment by onlaj** [comment]
You are right, I completely forgot about it, this port name was a placeholder. I'm going to fix it today.
