### ISSUE TITLE
61 keys

### ISSUE THREAD

**Issue by fischer6464** [onlaj/Piano-LED-Visualizer#40]
Thank you for providing this guide.

Is it possible to edit the code to use with a 61 keys keyboard?
How ?

**Comment by onlaj** [comment]
Hey, find in visualizer.py file number "176" (2 leds for every 88 piano keys), it should occur 4 times, and change it to "122". It should work.

**Comment by fischer6464** [comment]
Thnx

**Comment by fischer6464** [comment]
One more question, can I edit the number of skipped leds?

**Comment by fischer6464** [comment]
![349A446F-3C38-43F2-8B50-B5DF409CB978](https://user-images.githubusercontent.com/57663006/69798681-ceead900-11e2-11ea-9f8a-91f9c47539a5.png)

**Comment by onlaj** [comment]
This part of code (first 6 lines) is for fixing key spacing. So if the led lights up in the wrong place you can fix it by changing note_offset in specific keys range.

**Comment by fischer6464** [comment]
Great 
I made it work btw. Just need to edit the py file to fix the led numbers to 122.

You been a great help Onlaj 

Thank you
