### ISSUE TITLE
The proyecto works on the pi zero 2w

### ISSUE THREAD

**Issue by Orly1625** [onlaj/Piano-LED-Visualizer#408]
Hello I want to know if the proyect works fine in the raspberry pi zero 2w? Thanks you for excelent proyect.

**Comment by onlaj** [comment]
Hey.
There were some [problems](https://github.com/onlaj/Piano-LED-Visualizer/issues/296) at the beginning but now it should work just fine.

**Comment by Orly1625** [comment]
I can confirm that the project works perfectly on the raspberry pi zero 2w and is also much faster than the previous version
