### ISSUE TITLE
Can't seem to get the web interface/lights to work

### ISSUE THREAD

**Issue by TheGrand88** [onlaj/Piano-LED-Visualizer#412]
I had the lights and web interface working perfectly fine a few months ago. I moved, and it could be possible things got messed up during that process. 

I tried to get the lights to work last night, and the web interface worked just fine, the raspberry pi had its light on, it was just the lights that weren't working. So I assumed that I just needed to re-wire the setup. So I did that this morning, and now, neither the lights nor the web interface is working. I have not changed anything else except trying to re-wire it. I have tested the lights separately with the wires that they came with, and they all turn on just fine, so it is not the lights or the power source.

I am wondering, could my raspberry pi be broken? What do you think is the issue?

**Comment by onlaj** [comment]
Hello. 
Can you connect to Raspberry through SSH? If so, try running the Visualizer manually. 
First, disable the currently running service by using the following command: 
`sudo service visualizer stop`
Then, run the Visualizer using the command 
`sudo python3 /home/Piano-LED-Visualizer/visualizer.py.`
If you encounter any errors, please copy and paste or take a screenshot of them here.
