### ISSUE TITLE
(Question) Does Sevilla's Soft MIDI USB-USB work with an Android Tablet?

### ISSUE THREAD

**Issue by tutseryday** [onlaj/Piano-LED-Visualizer#417]
Not an issue, just a question. I don't have a PC near my piano, was wondering if this device works connected to an Android tablet (Galaxy Tab S7) if I get a USB to USB C adapter to plug the device to my tablet?

**Comment by onlaj** [comment]
If your piano works with tablet it _should_ also work with Sevilla's device.
