### ISSUE TITLE
Pi Freezes and I have to SSH to reboot

### ISSUE THREAD

**Issue by ezshre** [onlaj/Piano-LED-Visualizer#420]
Hihi, cool project. I got it workin and  been using it for 2 weeks but often times my Pi freezes (screen and webinterface stop working), and I can SSH into it to reboot it. I have Pi zero 2 w. Is there any way I can stop it from freezing? Happens frequently, sometimes takes hours and sometimes within 10 minutes it freeze. Thanks

**Comment by onlaj** [comment]
Hello.
It's difficult to guess what could be wrong.
Try to run Visualizer manually, through SSH.

First, disable the currently running service by using the following command:
`sudo service visualizer stop`
Then, run the Visualizer using the command
`sudo python3 /home/Piano-LED-Visualizer/visualizer.py`

Wait until it freezes and copy-paste the error here.
