### ISSUE TITLE
Raspberry pi zero wh is not available

### ISSUE THREAD

**Issue by Dilanka-lakshan** [onlaj/Piano-LED-Visualizer#43]
Raspberry pi zero is not available in the Ali Express  link you mentioned and its out of stock. I cant buy from amazon cuz there is some problem in there. So can u update a another seller with this item in Ali Express 
![20191129_185228](https://user-images.githubusercontent.com/58334191/69871687-7813fb00-12d9-11ea-98c9-b15814b4bc2c.jpg)

**Comment by Dilanka-lakshan** [comment]
![Screenshot_20191129-173010_AliExpress](https://user-images.githubusercontent.com/58334191/69872068-772f9900-12da-11ea-92b0-a5517eb46ed7.jpg)

**Comment by onlaj** [comment]
I updated the links.

**Comment by Dilanka-lakshan** [comment]
Can u please mention a cheap price from an another seller its 36 $. I am
from srilanka and. Its a big price when i convert it in to my currency.  It
like 36 × 180 = 6480 LKR
.

**Comment by Dilanka-lakshan** [comment]
Can i use 10v power supply to light up 100% 172 lights

**Comment by onlaj** [comment]
I didn't find it cheaper, maybe it is out of stock because of Black Friday, I don't know.

> Can i use 10v power supply to light up 100% 172 lights
You need 5V (Volt) and 11A (Ampere) to light them all @100% and white color.

**Comment by Dilanka-lakshan** [comment]
Thank you for your response. I ll see u soon.


See you later....
