### ISSUE TITLE
Web Interface access

### ISSUE THREAD

**Issue by clancel** [onlaj/Piano-LED-Visualizer#434]
Hi.  I'm trying to access the web interface through a browser because I wish to adjust the color setting.  However, I can't seem to locate the local address of my raspberry pi.  I logged into my network and couldn't find Raspberry Pi under connected devices. Do you have any idea how I can locate the IP address for my Raspberry PI?

**Comment by onlaj** [comment]
Hey, you can find some methods of finding IP here: https://github.com/onlaj/Piano-LED-Visualizer/blob/master/Docs/wifi_setup.md
