### ISSUE TITLE
Problems editing sequences

### ISSUE THREAD

**Issue by fermaton** [onlaj/Piano-LED-Visualizer#436]
Hello.
It seems that the web interface adds some unknown tags to sequences.xml file.
When adding "fading" option, instead of <speed>, it adds another tag with a different name (fading speed/), and that makes the interface web to crash.
Also, the scale option has some bug too, not adding the requested scale to the xml file.

**Comment by onlaj** [comment]
Hey, thank you for reporting this bug and sorry for late response.
[Fading already fixed](https://github.com/onlaj/Piano-LED-Visualizer/commit/d4402d971c01a655f05fce8470adbb209178a8a4) , I will take a look at scale option next.
