### ISSUE TITLE
No module named "websockets"

### ISSUE THREAD

**Issue by Escanor274** [onlaj/Piano-LED-Visualizer#439]
Hi,
i´ve just finished the installation und wanted to start the pi, but there is now an error. Any idea how to fix it?
I copied the terminal:

sudo -E python visualizer.py
  File "/home/pi/Piano-LED-Visualizer/visualizer.py", line 17, in <module>
    from webinterface import webinterface
  File "/home/pi/Piano-LED-Visualizer/webinterface/__init__.py", line 3, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

Sorry if its obvious for you, but i'm rly not a geeek und would be happy about some help :)

**Comment by onlaj** [comment]
Run 
`sudo pip3 install -r requirements.txt`

**Comment by Escanor274** [comment]
everything works fine now, thank very much. any way to give u a tip?
