### ISSUE TITLE
Display remains white

### ISSUE THREAD

**Issue by Escanor274** [onlaj/Piano-LED-Visualizer#440]
Hey, the visualizer worked absolutely fine at first, but now the screen doesn´t start, it is always white. It seems that only the screen has a problem because the leds react to the keyboard as they should. 
i have reinstalled the image several times now, but the screen is still not working. Unfortunately there is no error to see anywhere in the terminal.
any idea? :(

![Screenshot (9)](https://user-images.githubusercontent.com/88237724/235427668-e27d14a8-b2db-44a3-acee-405ce8ba8c45.png)

**Comment by Escanor274** [comment]
i just have used test_screen and nothing happened. 
pi@raspberrypi:~ $ sudo python3 /home/Piano-LED-Visualizer/tests/test_screen.py
**********Init LCD**********
***draw line
***draw rectangle
***draw text
pi@raspberrypi:~ $

**Comment by onlaj** [comment]
Hey,
I had this problem a few times, it fixed by itself after few hours.
You can also try to reattach the screen, maybe the pins are not connected correctly.

**Comment by Escanor274** [comment]
that´s what i think too. i will buy a new screen and test it.
thank you for answering

**Comment by Escanor274** [comment]
the old screen was indeed the problem. The new one works just as it should :)
