### ISSUE TITLE
when play piano only 1 led turn on, not 2...why?

### ISSUE THREAD

**Issue by montrix23** [onlaj/Piano-LED-Visualizer#46]
How I can turn on 2 lead at the same time?

**Comment by onlaj** [comment]
You mean that when you are pressing more than one key only one LED lights up?
Or that there is only one LED for each key and you would like two?
If you mean the second then it is like that by design, if it would light up two leds to each key then the light would not be aligned with keys.

**Comment by onlaj** [comment]
I added the option of lighting one key with 3 LEDs in the last update.
