### ISSUE TITLE
sometimes my raspi stops on this screen

### ISSUE THREAD

**Issue by hyuny223** [onlaj/Piano-LED-Visualizer#49]
sometimes my raspi stops on this screen
Is there a way to solve this problem?
![20191213_164101](https://user-images.githubusercontent.com/58837749/70788238-ccd46d00-1dd3-11ea-8e35-2292f0a2c703.jpg)

**Comment by onlaj** [comment]
Hey.
This is a screensaver, if you have keyboard connected it will exit this mode when you start playing. You can also hold KEY2 button.

**Comment by hyuny223** [comment]
I pressed KEY2 button but i didn't work.
So I always should turn off the device on the first attempt.

**Comment by onlaj** [comment]
Hold KEY2, not just press it.

**Comment by hyuny223** [comment]
When my device enter screen saver mode, it all stops. Time also does not go. Holding key didn't work... :(

**Comment by onlaj** [comment]
Oh, so it maybe crashes. Can you show me console output after the crash?

**Comment by hyuny223** [comment]
Sorry for troubling you. 
The picture I uploaded is the console output after the crash.
When it entered screensaver mode, screen got stucked like that.
For operation, I should unplug power cable.

**Comment by onlaj** [comment]
By console I meant the window in which you typed "sudo -E python visualizer.py". It should show information why it crashed.

**Comment by hyuny223** [comment]
ah! I misunderstood!
![20191213_204007](https://user-images.githubusercontent.com/58837749/70797890-d916f500-1de8-11ea-90c1-c6e65bbae4f9.jpg)

**Comment by onlaj** [comment]
You didn't even start the script.
Run it from the correct directory so you can see working menu on RPi screen and wait until screensaver starts. Then check console for errors.

**Comment by hyuny223** [comment]
I am not an English speaker, I am a coding beginner. So I don't know whether I exactly did what you said.
![20191213_213708](https://user-images.githubusercontent.com/58837749/70800987-fbad0c00-1df0-11ea-80d3-19fe8ccae425.jpg)

**Comment by onlaj** [comment]
Ok, so it crashes because you have no piano attached. I will fix that in next update. For now you can avoid getting this error by connecting your piano to RPi.

**Comment by hyuny223** [comment]
ah! thanks for your reply. I got it.
After solving this problem, what should I do to update?
type "sudo apt-get update"???

**Comment by onlaj** [comment]
https://help.github.com/en/github/using-git/getting-changes-from-a-remote-repository

**Comment by hyuny223** [comment]
Then I need to clone your git!
