### ISSUE TITLE
1.3 SPI LCD small and portrait

### ISSUE THREAD

**Issue by BeardedTony** [onlaj/Piano-LED-Visualizer#498]
LCD is displaying in portrait mode and super small. Its using like a 1/3 of the screen. Space not used is showing like still white noise. 
Raspberry Pi zero W, SPI 1.3 hat, visualizer 1.5v img used. It boots ok, i can access the webserver without problems.

**Comment by onlaj** [comment]
Hello.

> If you are using WaveShare 1.3inch 240x240 LED Hat instead of 1.44inch 128x128, edit accordingly: ExecStart=sudo python3 /home/Piano-LED-Visualizer/visualizer.py --display 1in3

https://github.com/onlaj/Piano-LED-Visualizer/blob/master/Docs/manual_installation.md#8-installing-piano-led-visualizer

**Comment by BeardedTony** [comment]
Thanks! that fixed it!
