### ISSUE TITLE
Led light color control request

### ISSUE THREAD

**Issue by Kliklijoker** [onlaj/Piano-LED-Visualizer#50]
Hi, Aleksander Evening, does this possible can control led with two different color for both hand? Like right assign as green and left assign as red.

**Comment by onlaj** [comment]
Hello.
Well, obviously piano doesn't know which hand did you use to press the key, but it is possible to split keyboard into two (or more) parts, each with own color.
I might add it in future updates, thanks for feedback.

**Comment by onlaj** [comment]
Hello.
I added a requested feature https://github.com/onlaj/Piano-LED-Visualizer/commit/7dda0e331fb916443a1137af1040b1ac551920f1
