### ISSUE TITLE
Segmetation fault and leds not matching keys

### ISSUE THREAD

**Issue by ozals** [onlaj/Piano-LED-Visualizer#51]
![image](https://user-images.githubusercontent.com/44003033/70870691-5d41b780-1f64-11ea-9733-49363f82a343.png)
When I click my leftmost key on my keyboard, the program crashes with this error. It might have something to do with my keyboard only being 61 keys, but I also followed the [tutorial on how to fix that](https://github.com/onlaj/Piano-LED-Visualizer/issues/40). The lights also aren't aligned with my keyboard.
![IMG_0284](https://user-images.githubusercontent.com/44003033/70870747-0e485200-1f65-11ea-8696-a6793ac95ca3.JPG)

**Comment by onlaj** [comment]
Hello.
Try to change
`note_offset = 2`
and
`note_offset = 1`
`note_offset = 0`
etc.
to something like 
`note_offset = 20`
`note_offset = 19`
`note_offset = 18`
You know what I mean? Just try different values.
You can also try to run tests/printmidimessages.py and press leftmost key on your keyboard to check note number.
