### ISSUE TITLE
only 176 LEDs work?

### ISSUE THREAD

**Issue by hyuny223** [onlaj/Piano-LED-Visualizer#53]
Hello. I have a question.
I bought 2m LED strip(144led per meter) and I connected all wires.
However, only 176 LED worked and the rest didn't.
(I have total 288 LED because of 2 meter strip)
Is it right response?
is there a way to make all LEDs work?

**Comment by onlaj** [comment]
Hi.
Unless you have piano with some extra keys 176 leds should be enough to cover them all. Just cut the unnecessary part.
