### ISSUE TITLE
Automatic bluetooth connection

### ISSUE THREAD

**Issue by bradliegek3** [onlaj/Piano-LED-Visualizer#57]
Hi Onlaj,

Thanks for your project!

I have a question about the bluetooth function.

Is the rpi supposed to always send a rpi bluetooth signal so I can connect it to my laptop? Because mine doesn't. When I start the rpi, piano and laptop; I first have to acces the pi with my laptop to excecute the command sudo btmidi-server -v -n "RPi Bluetooth".
Then I can search for a new bluetooth device and connect with rpi bluetooth.

When I restart everything and want to connect rpi bluetooth again, I first have to delete rpi bluetooth in my laptop and search for a new bluetooth device.
Otherwise I can't find rpi bluetooth in synthesia.

I hope you can help me with this issue.
Thank you in advance and a happy 2020!

**Comment by onlaj** [comment]
Hello.
Try to install Blueman (connect to your RPi with VNC), this software helped me a lot with managing bluetooth connections.

**Comment by bradliegek3** [comment]
Will try this tomorrow, thankyou

**Comment by bradliegek3** [comment]
Happy 2020 everyone.

I tried connecting with the help of blueman. The following occurs:

-I don't have to type anything in the console for RPi-Bluetooth to show up, so thats good. But, when I connect to RPi-Bluetooth with my laptop, I can not see RPi-Bluetooth in synthesia.

-If I connect to RPi-Bluetooth with my galaxy s8, I am able to see RPi-Bluetooth in synthesia. But, synthesia will not react to the piano keys being pressed.

Any idea's? (Yes I did all the synthesia steps to enable midi for windows and the dll file step.)

**Comment by onlaj** [comment]
> -I don't have to type anything in the console for RPi-Bluetooth to show up, so thats good. But, when I connect to RPi-Bluetooth with my laptop, I can not see RPi-Bluetooth in synthesia.

So the connection is visible on your PC? I had similar problem and it was because Windows thought that RPi BT is a headphone device. Reconnecting solved it.

**Comment by bradliegek3** [comment]
The connection is visible in a way. Windows can only see "unknown device". When I connect to that, I get 2 extra devices. One called Bluetooth LE Device .... and the other one RPi Bluetooth. It doesn't connect with RPi Bluetooth, but it only says paired. I can't connect with RPu bluetooth, only remove device. The other device is connected however and I can see my laptop is connectet with the RPi when I look at it via VNC. This does not work for synthesia however. Nothing shows up.

![image](https://user-images.githubusercontent.com/59207299/72225934-718cca80-358b-11ea-8da7-3e8aaaec70c6.png)

**Comment by bradliegek3** [comment]
> Hello.
> Try to install Blueman (connect to your RPi with VNC), this software helped me a lot with managing bluetooth connections.

With the help of blueman I am able to disconnect Bluetooth LE Device B827eb5d4445 and connect with RPi bluetooth.

Blueman calls the bluetooth LE device "handsfree" and calls RPi bluetooth "audio source". In windows you can see the little audio icon next to RPi-Bluetooth.

I do not know how to adjust this or how to fix this. As of this moment I am still not able to see RPi-bluetooth in synthsia.

**Comment by onlaj** [comment]
This is how connecting looks on my setup, I'm not sure how else I can help you
https://streamable.com/751sv
UI is not in english but you should figure it out.
Remember that you have to initiate connection from your PC, not the other way.

**Comment by bradliegek3** [comment]
Interesting. Does your RPi-bluetooth jump to the audio list by itself? By me it stays in the other devices list and stays on "paired" instead of connected :o

**Comment by onlaj** [comment]
Yeah, as you can see on video.
Try to wait for a while between each action. I cut some parts of video to make it shorter so you can't see, but I waited like 15 sec while it was searching for device, then another 15 after clicking "connect" etc.

**Comment by bradliegek3** [comment]
I will have another try at this tomorrow, thank you for replying.

The only thing odd still, is that it connects to that other "weird" bluetooth device simultaneously with RPi-Bluetooth.

**Comment by bradliegek3** [comment]
No idea what is happening with that stupid device anymore.
Before installing the bluetooth part, all led's work fine. After installing the bluetooth part, the led's glitch.
After installing the bluetooth part, no device is being found in windows. Only after I type sudo btmidi-server -v -n "RPi Bluetooth" in the console. I can find RPi-bluetooth in windows and synthesia recognizes it.

My hands are tied, no idea what to do. Every time I try it, I get another problem.

**Comment by vzoltan** [comment]
@bradliegek3 
so, how did you solve that part that synthesia now sees your rpi?
bc for me synthesia doesnt see my pi, im guessing bc windows connects to the pi as headset/audio device, not midi.

**Comment by bradliegek3** [comment]
@vzoltan  
Exactly as I wrote in that comment. I cannot get to get it working without typing that line.

I have not tried anything for a while because I moved to another house.
I will post again when I get any more progress.

**Comment by randaz81** [comment]
I have more or less the same questions.
I reached this point so far:

![Settings 2_27_2020 2_04_25 AM_LI](https://user-images.githubusercontent.com/2869969/75402654-af5c6d00-5905-11ea-9e8d-dbfa779c8c34.jpg)

I have two (can you explain me why two?) bluetooth devices displayed on windows, one is "connected", the other one is just "paired".

However, Synthesia is not able to detect the keyboard via bluethooth, even following the trick https://synthesiagame.com/forum/viewtopic.php?p=46920#p46920

The leds are working OK when I press the keys on my keyboard.
What else should I check?

**Comment by vzoltan** [comment]
You should name your bt midi server service different to see if you are connected to it or to the pi.

Also in the btmidi.service file set the sleep to 30sec.

Reboot and it should work.

**Comment by bradliegek3** [comment]
Unbelievable, it works!
