### ISSUE TITLE
Ws2813 wiring?

### ISSUE THREAD

**Issue by Dontbemadpls** [onlaj/Piano-LED-Visualizer#58]
I have a slightly different strip (ws2813), how should I wire it to the rpi? Is it possible without a level shifter?

What I am currently doing:
Data: gpio19
Clock:gpio23
GND to GND

**Comment by JAKJUS7** [comment]
Yes, As long as your power supply is only 5v 6a. I go with 
GND: Gpio 6
Data: Gpio 18
To which my data is directly hooked into my leds and my ground and 5v are connected to a Breadboard.
