### ISSUE TITLE
mido input list

### ISSUE THREAD

**Issue by hyuny223** [onlaj/Piano-LED-Visualizer#61]
I wrote that LEDs do not respond to key press.
I found that my piano name is not on the midi input list when I connected RPI to my piano.
But screen saver works well(the screen saver stops if it is not connected to the piano).
any solution?? :(

**Comment by onlaj** [comment]
What linux distribution do you have installed? On your screens I can see Debian, is it right? Maybe try to install Raspbian?

**Comment by hyuny223** [comment]
you are right. I installed this.

**Comment by onlaj** [comment]
Type
`aconnect -l`
in your console to check if your piano is visible on the list. If it's not I'm afraid I can't help you. This might be both hardware or software problem but not related to my code. Maybe your piano requires some drivers when using with Linux.

**Comment by hyuny223** [comment]
then it isn't related to whether debian or noobs?
very sad not to work.. thanks for your effort..!
