### ISSUE TITLE
No playback port & leds doesnt respond to keys

### ISSUE THREAD

**Issue by Roloo38** [onlaj/Piano-LED-Visualizer#62]
Hi there. I set up the raspberry after the github instructions, the leds are working with the strandtest.py examples, but when i connect my piano to the rpi, and run the command:
> sudo -E python visualizer.py

It show me the piano name, but says “no playback port” and the leds doesnt light up. Any ideea why?
I dont use synthesia btw, and i use “python3” because if i write only “python” it runs with pyton 2.7, which is not in use anymore (i think).

![845C3792-6FC7-48E2-AF43-5A2AB3C81E39](https://user-images.githubusercontent.com/55906704/71900404-70603580-3166-11ea-9127-b04217303693.jpeg)

**Comment by onlaj** [comment]
Don't worry about playback port.
I can see that your keyboard is seen by system as two devices. Try to change input in Visualizer menu (Port Settings -> Input) to something else.

**Comment by Roloo38** [comment]
@onlaj Thanks for the fast replay!! 
I’m a beginner at raspberry, so my question is: how do I change the input in visualizer?

 I dont use the little waveshare screen, i have the raspberry connected to a monitor with hdmi, keyboard and mouse.

**Comment by onlaj** [comment]
Oh, unfortunately you can't change any settings without screen hat, you would have to edit the code and set input as a fix name, then try all available ports.

**Comment by Roloo38** [comment]
And if i connect the led screen, i can change it directly?

Because i have the screen, but i didnt use it yet

**Comment by onlaj** [comment]
Yes, with screen connected you will have menu with all settings.

**Comment by Roloo38** [comment]
I connected the screen, and is white, nothing appears on it. So i was followed the instructions from “ https://neuma.studio/rpi-as-midi-host.html “, and i got some problems with “lcd-show.py” and with 

> lcd-show.py "first line" "second line" "here's a quite long line" "4th line of text"

> connectall.rb

Any ideea why?

![image](https://user-images.githubusercontent.com/55906704/71908675-23388f80-3177-11ea-8db3-56f93a72f76a.jpg)
![image](https://user-images.githubusercontent.com/55906704/71908720-33e90580-3177-11ea-95a4-ebb174760acc.jpg)

**Comment by onlaj** [comment]
You have to run visualizer.py to see menu.

**Comment by Roloo38** [comment]
I runned the visualizer.py and the screen is still white. I think i didnt set it up correctly. I followed the instructions on the neuma.studio website and i got an error with “lcd-show” which cannot be found
Any ideea why?

**Comment by onlaj** [comment]
You should only follow those parts of neuma tutorial:

- configuring automatic midi connection (this is required even if you don't need Bluetooth feature)
- midi bluetooth setup

Nothing more.

**Comment by Roloo38** [comment]
And for the screen is some code i need to run or just plug and play? Because the screen still doesn’t work even when i run the visualizer.py...

**Comment by onlaj** [comment]
If you connected it correctly it should work. Can you take a picture?

**Comment by Roloo38** [comment]
So I rebooted it and now work (sorry, my fault:)

I’m gonna connect the cables for leds, and let you know if it works

**Comment by Roloo38** [comment]
All is okay, working well. Thanks for your help and time!!
