### ISSUE TITLE
configure midi connection

### ISSUE THREAD

**Issue by Dilanka-lakshan** [onlaj/Piano-LED-Visualizer#63]
i cant configure midi connection using telnet. the interface of coding is like a mess and cant copy paste the codes and etc. what can i do
![2020-01-08](https://user-images.githubusercontent.com/58334191/71954700-1d40be00-320c-11ea-8f03-801aa3c83ce9.png)

https://www.youtube.com/watch?v=-I_73CZXyI8&t=76s  .................... i followed this youtube tutorial from ap piano

**Comment by onlaj** [comment]
Use SSH instead
https://www.putty.org/

**Comment by Dilanka-lakshan** [comment]
thak you. i finally manage to finish that but . after soldering wires to rp and to lcd the item is not powering p when using power adapter to power

**Comment by Dilanka-lakshan** [comment]
using dc power socket with the dc5v and 5a power adapter. why is that
