### ISSUE TITLE
No module named webcolors 

### ISSUE THREAD

**Issue by Crazy-Geeks** [onlaj/Piano-LED-Visualizer#75]
Hello. I have problem with installed webcolors, visualizer.py don't want to work
In python IDLE it works fine
I also tried to install webcolors manually from github, but the problem still exists
![webcolors](https://user-images.githubusercontent.com/39135096/73612353-04091280-45fc-11ea-9eb6-4798830d4888.PNG)

**Comment by onlaj** [comment]
Hi.
Correct command to launch script is
`sudo -E python visualizer.py`

**Comment by Crazy-Geeks** [comment]
I have just installed all libs by apt-get or from github (like apt-get install python-webcolors)
And after installing all the packets, my command works fine. Does it matter where the [-option] is?
I'll try correct command, but later
I used lite version of raspbian, it was needed to made 4GB distribution, instead of 9-10 GB

![](https://sun9-26.userapi.com/c855536/v855536160/1e5368/waVRIrBtTnc.jpg)

![](https://sun9-52.userapi.com/c855536/v855536186/1e988b/4B_JtxdYYdE.jpg)
