### ISSUE TITLE
Raspberry pi 4?

### ISSUE THREAD

**Issue by PIrKo** [onlaj/Piano-LED-Visualizer#76]
Hi, I can't get the zero w model. Anyone try on a rp4? and a touch screen? Thanks a lot

**Comment by Kadnium** [comment]
Rasperry pi 3 has issues with leds being delayed so rp4 might have the same problem. I had rp3 and had to buy zero because of that.

**Comment by PIrKo** [comment]
Thx i could buy the zero on aliexpress! thx

**Comment by spiccrix** [comment]
Quick note! I have the rpi4 (4gb Ram). When I launch the visualiser.py with python (2) it lags. When I do it with python3 it works wonders!! So, I knew it from the beginning, it is not acceptable that rpi4 couldn't handle a basic script perfectly. More, I run this script with two other scripts controlling 2 other led strips, and it still works normally with no lag. I hope all rpi4 owners see this and try this solution.

**Comment by spiccrix** [comment]
PS : to be able to run it with python3, you should install all needed python packages with "pip3" instruction

**Comment by vzoltan** [comment]
Hi, how fast is it to load a midi file?
