### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by eengamer** [onlaj/Piano-LED-Visualizer#80]
Todaz i set up mz raspberrz pi zero and forgot to setup the bleuthoot the first time after i got everything installed i realised mz mistake i added it afterwards but is doesnt show up on my phone how can i fix this?

**Comment by vzoltan** [comment]
1. first check in this app, if it sees, connect to it in it, then in the phone's bt settings.
https://play.google.com/store/apps/details?id=com.mobileer.example.midibtlepairing&hl=en

2. if this app cant see it, try to reset bluetooth in the visualizer menu on the pi, and then try step 1.

**Comment by eengamer** [comment]
I have done both steps still doesnt show up :/

**Comment by vzoltan** [comment]
ssh into you pi and check if BTMIDI server is up and running.
sudo systemctl status btmidi.service

now im almost sure, youll get an error.

**Comment by eengamer** [comment]
And what to do if it says error??

**Comment by vzoltan** [comment]
lets see what it says..

**Comment by eengamer** [comment]
Can we contact anywhere or do we do it via github

**Comment by vzoltan** [comment]
paste it here.

**Comment by eengamer** [comment]
![15825538664873198604726790338920](https://user-images.githubusercontent.com/61322147/75159649-d7d34400-5718-11ea-84c5-84fc0970c10b.jpg)

**Comment by eengamer** [comment]
Cant seem to find a error i think

**Comment by vzoltan** [comment]
one more thing to try on widnwos:
https://www.microsoft.com/en-us/p/midiberry/9n39720h2m05?activetab=pivot:overviewtab

if you see your BTMIDI in this on windwos, while on windows you see Connected to pi, 
should work.

(as for my, i only can use synthesia, when this midiberry makes the connection.)

**Comment by eengamer** [comment]
![15825555583626290145581530345912](https://user-images.githubusercontent.com/61322147/75161866-cbe98100-571c-11ea-844c-a80df9991ba5.jpg)
Didnt find anything

**Comment by vzoltan** [comment]
ok, its clear that you dont have connection to your pi via bt.
idk :(

try to do the
OPTIONAL MIDI BLUETOOTH SETUP at here:
https://neuma.studio/rpi-as-midi-host.html
again....

**Comment by eengamer** [comment]
![15825580290541241636404817944824](https://user-images.githubusercontent.com/61322147/75165338-8b8d0180-5722-11ea-9a65-c7151d1466c4.jpg)
I try reinsyreinstalling and this shows up

**Comment by vzoltan** [comment]
ich spreche nur ein bisschen deutsch ;) aber ich deneke du need to install other things too;)

maybe sudo apt install gcc
and then again...

**Comment by vzoltan** [comment]
what version of raspbian did you install on your sd?

**Comment by eengamer** [comment]
Could we get contact on discord if that command doesnt wirk since i tried alot of things but havent got it working yet

**Comment by eengamer** [comment]
> what version of raspbian did you install on your sd?

The latest version

**Comment by eengamer** [comment]
![1582563216312637312033023248945](https://user-images.githubusercontent.com/61322147/75173075-9c437480-572e-11ea-8a39-411a291264f1.jpg)
WhoWhole time it says libudev is required but i cant install it im getting errors

**Comment by eengamer** [comment]
![1582563478351560872813401355380](https://user-images.githubusercontent.com/61322147/75173489-3dcac600-572f-11ea-82ba-75ad0e9b9419.jpg)
