### ISSUE TITLE
left hand/right hand colors

### ISSUE THREAD

**Issue by randaz81** [onlaj/Piano-LED-Visualizer#83]
In Synthesia I have blue/green colors for left/right hand.

In the visualizer LCD options instead, I was able to find the options:
- solid color (all leds are set to the same color)
- multicolor (I set the color for the each range)

Unfortunately, in multicolor mode, the color range does not automatically corresponds to the one shown on synthesia. I mean, in synthesia the range might vary during the song (I can even play blue notes with my left hand on the right of the green notes of my right hand!)

I wonder if my conclusions are correct (and this feature is not yet implemented), or if I am missing something some option to copy the colors of synthesia on the LED strip by setting different colors to different midi channels?
 Thank you!

**Comment by randaz81** [comment]
Haaaa I just discovered the setting **finger-based channel** in the **key lights** menu of Synhtesia. It works perfectly! 
Please add this info to your documentation, it was not explained at all.
Awesome piece of software, thank you!

**Comment by onlaj** [comment]
> Please add this info to your documentation, it was not explained at all.
I will, thanks.
