### ISSUE TITLE
Waveshare Installation/White Screen

### ISSUE THREAD

**Issue by xsound09** [onlaj/Piano-LED-Visualizer#89]
Hey there,

Is there further installation required for the Waveshare screen other than the instructions here? My screen only shows white when plugged in, I have followed all the instructions here, and also the manufacturer's instructions (afterwards, since it isn't working).

I am wondering if my Waveshare screen is faulty, haven't seen a single graphic on it other than blank white. Any advice? Thanks!

**Comment by onlaj** [comment]
It might be a stupid question, but did you launch visualizer.py script?

**Comment by xsound09** [comment]
@onlaj Yes, nothing happens on the visualizer when launching the script. I'm mostly curious if there's outside installation required for the screen beside your instructions because the instructions the manufacturers provide have bad English so I'm wondering if I installed it incorrectly with their instructions, or if that's even relevant if I correctly follow yours.

**Comment by onlaj** [comment]
What does the console say?

**Comment by xsound09** [comment]
@onlaj My apologies for the delay. When I run sudo -E python visualizer.py the console says: 

Inport set to Keyboard:Keyboard MIDI 1 20:0
Inport set to Keyboard:Keyboard MIDI 2 20:1
playport set to Keyboard:Keyboard MIDI 1 20:0
playport set to Keyboard:Keyboard MIDI 2 20:1

But, nothing else happens. The waveshare screen remains white.

**Comment by onlaj** [comment]
Try to run some example code to check if everything works correctly
https://www.waveshare.com/wiki/File:1.44inch-LCD-HAT-All-Code.7z

**Comment by xhosan** [comment]
I am having the same problem as well. I checked the physical connections and everything seems okay, trying the example code now.

**Comment by xsound09** [comment]
@xhosan How did the example code run for you? I haven't been able to check yet, since I have to disconnect my work monitor to test. Thanks for your help @onlaj I will be checking soon

**Comment by xhosan** [comment]
@xsound09 I ran each of the programs in the file, still a blank white screen for all of them. Here's what was on my console for key_demo.py and main.py, they were the only programs that logged anything. Not sure if this helps or not but thanks @onlaj for everything!
`
pi@raspberrypi:~/RaspberryPi/python $ sudo -E python key_demo.py
key_demo.py:21: RuntimeWarning: No channels have been set up yet - nothing to clean up!  Try cleaning up at the end of your program instead!
  GPIO.cleanup()
^CTraceback (most recent call last):
  File "key_demo.py", line 100, in <module>
    disp.LCD_ShowImage(image,0,0)
  File "/home/pi/RaspberryPi/python/LCD_1in44.py", line 310, in LCD_ShowImage
    pix = pix.flatten().tolist()
KeyboardInterrupt
pi@raspberrypi:~/RaspberryPi/python $ sudo -E python main.py
**********Init LCD**********
***draw line
***draw rectangle
***draw text
pi@raspberrypi:~/RaspberryPi/python $
`

**Comment by imagemas** [comment]
Help. mistakenly ordered another screen.
Waveshare 1.3inch OLED HAT, OLED дисплей 128×64px
How can i use it?
![DOC003769472](https://user-images.githubusercontent.com/66170486/83488484-47af5280-a4f0-11ea-8eae-21f835aefce5.jpg)

**Comment by onlaj** [comment]
@imagemas you can't, at least not without making a lot of changes in code, sorry.
