### ISSUE TITLE
How to adapt the project to a 3.5 inch Touchscreen ?

### ISSUE THREAD

**Issue by spiccrix** [onlaj/Piano-LED-Visualizer#90]
What should I change so that I can display the program in a 3.5 inch Touchscreen like in this bundle : https://www.aliexpress.com/item/4000244917268.html?spm=a2g0s.9042311.0.0.56d64c4dKJN56C ?

**Comment by onlaj** [comment]
You would have to make a lot of changes inside MenuLCD class. 3.5 inch screen doesn't have any buttons so you would have to add support for touch screen.
Besides, many users reported delay problem when using Visualizer with RPi3, it can be the same with 4.
I recommend to buy 1.44inch screen and RPi Zero WH.
