### ISSUE TITLE
Nothing is working 

### ISSUE THREAD

**Issue by eengamer** [onlaj/Piano-LED-Visualizer#91]
Hello, i have recently got my pieces and out ecerything togheter the first time my pi died and i got a replacement. Now when i try it the pi gets really hot the program freezes instantly the leds have neverworked on the pi. I use a 5v 10a psu from meanwell i have tried alot do i need to get another replacement or is the sd faulty. Pi gets hot even without sd card. This is getting pretty annoying for me since nothing works. Hope you can help me?

**Comment by onlaj** [comment]
Did you try running test programs from here?
https://tutorials-raspberrypi.com/connect-control-raspberry-pi-ws2812-rgb-led-strips/

**Comment by eengamer** [comment]
I have tried evrything but it wont work my second raspberry pi is also broken it get so hot that it almosr burns you the program freezes immideatly wenn i get an replacement can we get in a call an make together?

**Comment by vzoltan** [comment]
Raspbian lite or full desktop?

**Comment by eengamer** [comment]
Full  the programm works but when i connect the leds noting works and 2 time my pi broke now it starts get really hot freezes and reboots

**Comment by onlaj** [comment]
Are you sure you connected the wires correctly? Try to unplug and check if RPi is getting hot without them.

**Comment by eengamer** [comment]
It gets hot without them because it brike when i had everything connected and the lights wouldnt go on or work

**Comment by Jaxii** [comment]
I suggest buying a new Pi, perhaps one from a reputable supplier.

**Comment by eengamer** [comment]
Is there anyone that could help me as soon as i get my replacement pi??
