### ISSUE TITLE
I cant run visualizer.py

### ISSUE THREAD

**Issue by Roloo38** [onlaj/Piano-LED-Visualizer#92]
Hi there. After i installed everything, when i try to run the visualizer, i got this, and nothing happens.
![3E7FD5D2-7064-4627-BB8D-5817893AC3FC](https://user-images.githubusercontent.com/55906704/76264294-0b11e900-626a-11ea-9227-177f8f700eaf.jpeg)

**Comment by onlaj** [comment]
Did you [enable SPI](https://www.raspberrypi-spy.co.uk/2014/08/enabling-the-spi-interface-on-the-raspberry-pi/)?
What Raspbian version do you have?

**Comment by Roloo38** [comment]
oh, yes, I forgot about enable SPI. thanks
