### ISSUE TITLE
After a minute the program stop working

### ISSUE THREAD

**Issue by Roloo38** [onlaj/Piano-LED-Visualizer#93]
Hello, after a minute that I run the code, the screen no longer works, it remains blocked, and the LEDs either do not work or remain blocked on the piano keys pressed last time.
If you think it will help, i can share a video with you.
![7C3EFDD9-B314-467A-A408-96D3A8DD1394](https://user-images.githubusercontent.com/55906704/76544753-3f1b2300-6491-11ea-8aa8-4fe295271285.jpeg)
pressed last time

**Comment by onlaj** [comment]
What does the console say?

**Comment by Roloo38** [comment]
Nothing. I attach a photo. Sometimes it works...sometimes it doesn’t 
![A06C1506-7DBA-41CE-B9CC-A1767ED55300](https://user-images.githubusercontent.com/55906704/76545659-d634aa80-6492-11ea-9a26-697e9a6a9327.png)

**Comment by Roloo38** [comment]
I think I figured it out...i was using a iphone terminal, and when the app shut down, the raspberry freeze..sorry for bothering you

**Comment by vzoltan** [comment]
either put & at the and, or run it as a service.

**Comment by Roloo38** [comment]
Ok, thanks!
