### ISSUE TITLE
Sugestion for leds wires and screen

### ISSUE THREAD

**Issue by Roloo38** [onlaj/Piano-LED-Visualizer#94]
for those who use raspberry 2/3/4 b + and do not want to solder the wires on the pins, under the screen, I found a cheap and good solution.  this pin extension board can be used to connect the screen but also to connect the LEDs to the pins. I will attach some photos and a link.

RON 9.34  24％ Off | Raspberry Pi GPIO Extension Board 1 to 3 40 Pin GPIO Module for Orange Pi PC Raspberry Pi 4B/3B+/3B Raspberry Pi Zero W/1.3
https://a.aliexpress.com/_dVErxlT

* i put some tape on the second row of pins to not touch my screen

![EF00AB94-F38F-4F85-8FC9-D0057432213D](https://user-images.githubusercontent.com/55906704/76562632-76e49380-64ae-11ea-8b8e-c49b15ec6185.jpeg)

![0472A473-3F20-4C94-9D7F-80C8A84A9C99](https://user-images.githubusercontent.com/55906704/76562636-7815c080-64ae-11ea-8fa3-b86fcbdf0cb6.jpeg)

![D9BDCC1E-38AD-40E3-B69E-F0F279DDDA38](https://user-images.githubusercontent.com/55906704/76562623-71874900-64ae-11ea-8ecb-07e9321281ab.jpeg)

![E0054664-A78C-42C8-BFCB-E775C214CFF8](https://user-images.githubusercontent.com/55906704/76562637-7946ed80-64ae-11ea-84ab-be0204e9b420.jpeg)

**Comment by onlaj** [comment]
I used something like this
![piface-shim-io-nakladka-prototypowa-dla-raspberry-pi](https://user-images.githubusercontent.com/9073428/78246941-43fc5100-74ea-11ea-8ad2-aa0b2f4a734e.jpg)
and it worked too, but it wouldn't fit the case.

What version of RPi do you use? Do you have any latency issues?

**Comment by vzoltan** [comment]
@Roloo38 hi

could you / would you pls share the source of your led profile?
i cant find a nice thin and clean like yours or @onlaj 's  (only in poland, but that store wont deliver to me :( )

Thank you

**Comment by Roloo38** [comment]
@onlaj hi, and sorry because i didn’t responded. I use raspberry pi 3B+, and i don’t have any latency problem, everything works fine :). My gpio adaptor fits perfectly on rpi, and in the case

**Comment by Roloo38** [comment]
@vzoltan hi, sorry for late response. I buyed my led profile from a store in my country (Romania), and i don’t think they deliver out of the country. Sorry :(
