### ISSUE TITLE
Script not booting up

### ISSUE THREAD

**Issue by eengamer** [onlaj/Piano-LED-Visualizer#95]
Hello today the script and led worked fine i also today added samba file sharing to the pi after that i pluged it in and everything worked fine. I then shutted it off and when i came back to play again it was on white screen zo i unplugged it and put it back in again and it wont boot up to the programm

**Comment by eengamer** [comment]
Note i also did switch from autologin console to desktop amd then switched back

**Comment by eengamer** [comment]
![20200317_092440](https://user-images.githubusercontent.com/61322147/76836478-2f089800-6831-11ea-88b8-e049159d6fe0.jpg)
This is what i says when i plug it in

**Comment by eengamer** [comment]
![20200317_092550](https://user-images.githubusercontent.com/61322147/76836591-5ceddc80-6831-11ea-832c-35cecfecd242.jpg)
This is what it says

**Comment by onlaj** [comment]
Looks like your settings.xml is damaged, try to clone it again.

**Comment by eengamer** [comment]
did it and it now works
