### ISSUE TITLE
My ledstrip not working

### ISSUE THREAD

**Issue by eengamer** [onlaj/Piano-LED-Visualizer#97]
Hello onlaj my led strip worked fine till today but today it stopped working ik made sure all connections are good. And i can play the La campanella file on the pi to piano. But mynkeds are not worki
![20200325_144558](https://user-images.githubusercontent.com/61322147/77648067-d1c6c200-6f67-11ea-9004-e2af75638f10.jpg)
![20200326_134041](https://user-images.githubusercontent.com/61322147/77648076-d8edd000-6f67-11ea-9227-b6568d59e797.jpg)
![20200326_134055](https://user-images.githubusercontent.com/61322147/77648104-e60abf00-6f67-11ea-9443-99c90e2cde4e.jpg)n

ng at all

**Comment by vzoltan** [comment]
try with the PIN #12  (the green cable)
also modify change it in visualizery.py to 12 from 18
and give it a try again. 

This line:
`self.LED_PIN        = 18      # GPIO pin connected to the pixels (18 uses PWM!).`

**Comment by eengamer** [comment]
What do you mean witch pin is 12 and where do i change it

**Comment by vzoltan** [comment]
re-wire to pin12 from pin18 on the pi, physically .

**Comment by eengamer** [comment]
But where is pin 12 and where can i find the commdan line to change soory im not so good in this

**Comment by vzoltan** [comment]
gpio12
![Capture](https://user-images.githubusercontent.com/2751780/77651401-05581b00-6f6d-11ea-87a2-2f86ec77022c.JPG)

**Comment by eengamer** [comment]
How do i accses visualiser.py?

**Comment by eengamer** [comment]
I do have telnet enabled

**Comment by eengamer** [comment]
![20200326_143713](https://user-images.githubusercontent.com/61322147/77652932-55d07800-6f6f-11ea-81c8-c3f7b35f7025.jpg)
Like this

**Comment by eengamer** [comment]
![20200326_144102](https://user-images.githubusercontent.com/61322147/77653381-dee7af00-6f6f-11ea-95dc-792801b1b1fa.jpg)
Still doesnt work

**Comment by vzoltan** [comment]
then check somehow your ledstrip if it works or not.

**Comment by eengamer** [comment]
The led strip worked fine yesterday and today when i put the piano and things on it complete did nothing

**Comment by eengamer** [comment]
It is not the led strip i teste an other one that also didnt work

**Comment by onlaj** [comment]
Can it be your power supply? As long as you don't light more than few leds at the same time you should be able to power it directly from RPi, just for testing.
![led_strips_raspi_NeoPixel_bb](https://user-images.githubusercontent.com/9073428/77675956-f5046800-6f8d-11ea-87a3-494eb4e34373.png)

**Comment by eengamer** [comment]
Do i need to run anything for it? Like an script

**Comment by onlaj** [comment]
Yes, you can find examples here: https://tutorials-raspberrypi.com/connect-control-raspberry-pi-ws2812-rgb-led-strips/
Just change number of leds to something low, like 10, so RPi can power it.

**Comment by eengamer** [comment]
I think its the powersupply i will try and get a replacement

**Comment by eengamer** [comment]
Hey i think its the psu i didnt do a command just connected everyrhing and ran the visualiser.pythe furst led was blinking really so i know its the psu

**Comment by eengamer** [comment]
Hello onlaj i have got my new powersupply today and it still isintnworking what could be the problem i have reinstalled the script bit still no working leds. 1 led on my strip looks like this mayby that could be it but i dont think that bcs the other ledstrip doesnt have that
![20200402_132115](https://user-images.githubusercontent.com/61322147/78251888-4b275d00-74f2-11ea-9eb0-f81115a39467.jpg)

**Comment by onlaj** [comment]
You said that without power supply it works, can you confirm?

**Comment by eengamer** [comment]
I didnt change anything just put the effect on rainbow and connevted it the first led was softly flickering so it should be fine but i cant seem to find the problem

**Comment by onlaj** [comment]
Can you connect it like on last image I send, so the whole strip is powered directly by Pi?

**Comment by eengamer** [comment]
Thats what i have done and then powered the script and started rainbow effect it was flickering really softly

**Comment by onlaj** [comment]
So it doesn't work properly, right? Then it must be either led strip or your Pi, but you said it's the same with two different strips, so it must be RPi. Does it make sense?

**Comment by eengamer** [comment]
I think it could be the led strip since the first led looks burnt as shown in the picture

**Comment by vzoltan** [comment]
if that bothers, cut it off, and re-solder the wires

**Comment by eengamer** [comment]
I dont have a soldering pen but i have to send the led strip back so they can provide a new one
